### ISSUE TITLE
Bugs bummy and Taz time buster(ntscu tested) regression?

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#1]
the sound is speeded up to hell and then before the game starts the sound stops and makes the emulator crash, on the official wiisxrx while the sound is off sync and repeating loop the game can be played fine i took a picture of the crash, not sure if it helps since im guessing the game is crahsing because its playing way too fast.
![IMG_20220625_080521](https://user-images.githubusercontent.com/12446178/175763258-f5dbf624-4d06-415b-b32f-cae44b999ceb.jpg)

still amazing work the compatibility and sound are on another level, thanks for you amazing work for wii/wiiu users.

**Comment by xjsxjs197** [comment]
It may be related to the problem of [sound high-pitched/faster]. 
After the next version is released, please reconfirm. 
At least the latest version of my local version can run normally, but the speed is a little slow.
