### ISSUE TITLE
Destruction Derby Raw menu issue 

### ISSUE THREAD

**Issue by ghr89** [xjsxjs197/WiiSXRX_2022#100]
Hi xjsxjs
Destruction Derby Raw have a issue in menu, run very slow.
Emukidid fix this in WiiSX, please, fix this in WiiStation 

![Screenshot_20230619-203357](https://github.com/xjsxjs197/WiiSXRX_2022/assets/23174459/a25e3c10-afd6-4e46-ad5e-3be33868e767)

Post in thread 'WiiSX / CubeSX (PCSXGC) with Lightrec Project - Beta testers & feedback needed!' https://gbatemp.net/threads/wiisx-cubesx-pcsxgc-with-lightrec-project-beta-testers-feedback-needed.626800/post-10187468

**Comment by saulfabregwiivc** [comment]
This fix is because it was integrated on Lightrec.
@xjsxjs197 needs to recompile the latest commits of Lightrec / GNU Lightning with the current toolchain he's/she's using.
