### ISSUE TITLE
CDDA music/track support broken as of commit a6ed0bd

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#101]
The Compact Disc Digital Audio (CDDA) music and tracks support now it's broken starting from commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/a6ed0bd10404d183c4aca5feb38d0d170e780946.

Before that commit, the CDDA tracks played fine.
The affected games by this includes: Grand Theft Auto, Ridge Racer Revolution, Vib-Ribbon, etc.

Any fix?

**Comment by ghr89** [comment]
I have tested destruction Derby and destruction Derby 2 and cdda not played, only SFX audio

**Comment by xjsxjs197** [comment]
Corrected the logic of ISOreadCDDA and resolved this issue
