### ISSUE TITLE
broken guitar audio

### ISSUE THREAD

**Issue by Mariofan1995** [xjsxjs197/WiiSXRX_2022#102]
In um jammer lammy, the player's audio is a seperate file, and the audios broken. please fix it, thanks :D

**Comment by saulfabregwiivc** [comment]
It should be fixed with latest DFSound implementation in the branch RearmCdromCdiso, but we're still working in it.

**Comment by xjsxjs197** [comment]
Try the following version, the problem should have been resolved. If the problem persists, try the old dynamic compilation core.
[boot20231127.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13469507/boot20231127.zip)
