### ISSUE TITLE
Tales of Destiny Crashes bringing up menu in battle screen

### ISSUE THREAD

**Issue by CaryGrantX** [xjsxjs197/WiiSXRX_2022#109]
Tales of Destiny works perfect except when you press Triangle to bring up menu in a battle screen.  It then hard crashes with an error code and the wii needs to be power cycled.  Error dump attached:

![TalesOfDestinyCrash](https://github.com/xjsxjs197/WiiSXRX_2022/assets/140980949/9b6a8ed6-e708-4696-a541-96ef936ee902)

Using Boot from Bios, Bios SCPH1001.bin

**Comment by xjsxjs197** [comment]
Try the following version, the problem should have been resolved. If the problem persists, try the old dynamic compilation core.

[boot20231127.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13469491/boot20231127.zip)
