### ISSUE TITLE
gameid from previous game when loading another game

### ISSUE THREAD

**Issue by eku** [xjsxjs197/WiiSXRX_2022#12]
According to [this thread](https://gbatemp.net/threads/wiisx-gameshark-v5.300994/), `WiiSX/WiiSX RX/WiiSXRX_2022` doesn't clear the old gameid before loading a new game. So this makes the usage of `Gameshark v5` tricky.

Could you please have a look at this and fix it. Thanks in advance.

**Comment by xjsxjs197** [comment]
Copy that. I'll try to fix it

**Comment by xjsxjs197** [comment]
It's really strange. I tried several games. It should be possible to get gameid.
Can I see your game information, just like the screenshot. 
![2022-07-06_174537](https://user-images.githubusercontent.com/31617363/177523169-04f0b5c7-69df-4148-84f0-72ddb4ede6ee.jpg)
![2022-07-06_174712](https://user-images.githubusercontent.com/31617363/177523182-61684a5f-9d79-42a0-8c2d-f9e14bfdd351.jpg)

**Comment by eku** [comment]
Could it be that you've already fixed this bug that's still in WiiSX RX? Do you have any commit that I could look after?

**Comment by xjsxjs197** [comment]
Sorry, I have to reproduce this error to correct it. Can you provide the game file

**Comment by xjsxjs197** [comment]
There should be no problem with the latest version,Because the ID of the Rayman has always been 99999, it is not affected by the previous game
