### ISSUE TITLE
(Question) Possibility of adding ICache emulation on Lightrec core implementation too?

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#129]
So, i've seen this old commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/109c5c1302691f013b65b38012180c47d5952a83

Which fixed Xenogears and also fixed a little bunch of other games (EA Sports F1 2000, EA Sports F1 Championship Season 2000) when trying to boot in the improved PPC dynarec, and Interpreter.

But now, if trying to boot those games (specifically the EA F1 ones) with Lightrec, they crash at the loading screen when you try to start a race, and after close investigation, i noticed there's no ICache emulation in Lightrec.

Seeing PCSX-ReARMed code ( http://github.com/libretro/pcsx_rearmed ), i noticed that they added ICache emulation for Lightrec too so these are bootable and playable there.

So, here's my question: is there any chance for implement ICache emulation to Lightrec basing in the actual implementation from PCSX-ReARMed? Thanks :)

**Comment by xjsxjs197** [comment]
Let me read the PCSX-ReARMed code and try to modify it, but the work is too busy and the progress may be slow

**Comment by xjsxjs197** [comment]
@saulfabregwiivc  
I'm not sure if it's appropriate to ask here, but I would like to know if the various features added by Jokippo in the latest main branch's code are still functioning properly. While I have tried my best to ensure that the merged code includes these features, I am unsure if they are running correctly. Would you be able to help confirm this from your end?
Thank you very much !

**Comment by saulfabregwiivc** [comment]
> @saulfabregwiivc I'm not sure if it's appropriate to ask here, but I would like to know if the various features added by Jokippo in the latest main branch's code are still functioning properly. While I have tried my best to ensure that the merged code includes these features, I am unsure if they are running correctly. Would you be able to help confirm this from your end? Thank you very much !

sure no problem, when i get free time i will test properly everything.
Right now i'm busy. See ya later!

**Comment by saulfabregwiivc** [comment]
Hi there, i tested latest builds of WiiStation recently, and i remembered about those games that needed ICache.

All i've tried worked fine on Lightrec and PPC dynarec for now, **but EA Sports F1 2000 still crashes when trying to start a race in Lightrec, but it works fine in PPC dynarec.**

Unsure what's happening now...

**Comment by xjsxjs197** [comment]
When these two games(EA Sports F1 2000, EA Sports F1 Championship Season 2000) are running on Dolphin in my local area, an error message box appears. After ignoring it, they can run normally. There may be issues on the Wii physical machine.
Both new and old dynamic compilation cores have the same issue.

**Comment by saulfabregwiivc** [comment]
The requirements here are made, there's ICache emulation on Dynarec and partial implementation/ICache hacks for Lightrec, closing for now.
