### ISSUE TITLE
sound high-pitched/faster

### ISSUE THREAD

**Issue by xjsxjs197** [xjsxjs197/WiiSXRX_2022#13]
from: [niuus](https://gbatemp.net/members/niuus.384984/)
sound is specially different in all games, as it is a bit high-pitched/faster in _2022, and will 'feel' kind of strange. Depending on your familiarity with the games, you can quickly spot it. Popular examples would be Street Fighter or Mortal Kombat games, with the announcers/special powers/music sounding accelerated

**Comment by saulfabregwiivc** [comment]
i was also reporting this.

I also heard the high-pitched music, mostly i've noticed it when booting the BIOS.

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 Is there any chance for see in the audio code for solve the problem of high-pitched audio?

**Comment by xjsxjs197** [comment]
> @xjsxjs197 Is there any chance for see in the audio code for solve the problem of high-pitched audio?

Let me try. This is also a key correction in the future, but I don't know how long it will take

**Comment by xjsxjs197** [comment]
The conversion error from 44100 to 48000 should be corrected. It can be significantly improved through BIOS startup.

**Comment by saulfabregwiivc** [comment]
The audio pitch is now corrected. I just compiled the recent main branch code and it now works. (through i did a very small testing). Thanks!

**Comment by saulfabregwiivc** [comment]
Update: now CDDA audio it's also high-pitched/accelerated, see issue https://github.com/xjsxjs197/WiiSXRX_2022/issues/26

But the other audio is fine.
