### ISSUE TITLE
[FR] Swap audio channels

### ISSUE THREAD

**Issue by malvarenga123** [xjsxjs197/WiiSXRX_2022#137]
Hello, when playing Akumajou Dracula X, I've noticed that the left and right channels are swapped, but the cables are correct (red and white). So I'd like to request an option to reverse the right and left channels in the emulator.

**Comment by xjsxjs197** [comment]
This issue was discovered before, and I thought no one cared about it(^_^). I'll fix it later

**Comment by gamecubefan1990** [comment]
Yes, I have the same problem with the swapped sound.
The best way to see this is with the game “Pong”.
When the ball hits the left side, the sound comes from the right speaker.
WiiSX 4.0 Playstation Emulator from emukidid does not have this problem.

**Comment by xjsxjs197** [comment]
When playing audio, the left and right audio channels have been swapped.
