### ISSUE TITLE
FPS drops with SLPM-86023 in CCD/IMG/SUB format

### ISSUE THREAD

**Issue by malvarenga123** [xjsxjs197/WiiSXRX_2022#139]
I've posted about it in the GBATemp thread, but I think it should be tracked here.
I think there's a bug handling CCD/IMG/SUB files.

Wii SD card
CCD/IMG/SUB - Oscillating FPS between 59.81 and ~58 and noticeable stutter (a little less than with USB)
BIN/CUE - Steady 59.81 FPS, no stutter
CHD (Deflate+FLAC) - Steady 59.81 FPS, no stutter

USB
CCD/IMG/SUB - Oscillating FPS between 59.81 and ~56 and noticeable stutter
BIN/CUE - Steady 59.81 FPS, no stutter
CHD (Deflate+FLAC) - Steady 59.81 FPS, no stutter

It's important to know that both BIN and IMG files are identical (same size and hashes).

**Comment by saulfabregwiivc** [comment]
I think it's because of the handling of these in the CDROM/CDRISO codes.

Right now we're updating these with the ones from PCSX-ReARMed, so when a new version is released it should be fixed.

**Comment by xjsxjs197** [comment]
Give the latest version below a try and see if the issue has been resolved.

[boot20231108.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13293563/boot20231108.zip)

**Comment by malvarenga123** [comment]
Sorry for the late reply.
But it still stutters with CCD/IMG/SUB. I have both images on the same card and same directory. It stutters immediately after loading a save with the CCD file and works smooth with BIN/CUE.

In case you want to test it, here are the CCD, SUB and CUE files (no game file):
[Akumajou Dracula X - Gekka no Yasoukyoku (Japan) (Rev 2).zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13430888/Akumajou.Dracula.X.-.Gekka.no.Yasoukyoku.Japan.Rev.2.zip)

The resulting BIN/IMG files will have the following hashes:
CRC-32: 37970f2f
MD5: 89120e71cdd77f5fb1f674c448d222b8
SHA-1: 340758588aa1d4f7293ffc8515634e283a6f57b2

The patch can be found here: https://www.romhacking.net/translations/1427/

**Comment by xjsxjs197** [comment]
Finally understood the reason for this issue, When using the [CCD/IMG/SUB] method, because it is necessary to frequently read the [SUB] file data, additional calls to fseek and fread operations are made, which slightly increases the cost of time compared to other methods. 
This issue cannot be solved, so we can only use other ways to play the game. This issue is closed

**Comment by malvarenga123** [comment]
That's good to know.
I suggest removing support for this format completely then. Leaving just cue/bin and chd will be easier to maintain and debug.
For games that have libcrypt protection, people should use: https://github.com/alex-free/libcrypt-patcher
