### ISSUE TITLE
Need for speed  No controller input.

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#14]
like i said i tryed standard and analogue and the game has no controller input at all.

**Comment by xjsxjs197** [comment]
Please tell me the ID of the game so as to correct the problem

**Comment by carnage702** [comment]
> Please tell me the ID of the game so as to correct the problem

SLUS-00204 pal version does it too (SLES-00223) and im guessing every version off this game, not sure if there is a jap one

**Comment by xjsxjs197** [comment]
Corrected sio waiting time, This issue should be corrected

**Comment by saulfabregwiivc** [comment]
Tested this commit, and Need for Speed now can be played (now it has controller input). Thanks!
