### ISSUE TITLE
Swapping game discs on various games (Driver 2, Metal Gear Solid, Vib-Ribbon, etc.) being broken on RearmCdromCdiso

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#148]
From GustavoReis (@ghr89) in GBAtemp:

On **Driver 2 (USA) (v1.1)**, if I try to change the discs, it doesn't identify it either, it just says "incorrect disc inserted".

Testing latest changes from the branch **RearmCdromCdiso** ( https://github.com/xjsxjs197/WiiSXRX_2022/tree/RearmCdromCdiso ).
Not sure from what exact commit caused this issue, but this issue doesn't let play the full game of Driver 2 (2 discs).
Any fix for this?

I will leave a memory card (.mcd) file for quickly reproduce the issue:
[SLUS01318.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13047002/SLUS01318.zip)

For reproduce:
1. Put the memory card save file in wiisxrx/saves/
2. Load **Driver 2 (USA) (Disc 1)** on WiiStation
3. Enter to "Undercover" mode, then "Load Game"
4. Load the savefile as normally do
5. The game will ask you to swap to Disc 2, go to the emulator menu, then go to "Current ISO" and select "Swap CD".
6. Load **Driver 2 (USA) (Disc 2)**
7. It should be displayed the disc was swapped, but it's still displaying "INCORRECT DISC INSERTED".

**Comment by saulfabregwiivc** [comment]
Update: this issue happens on all PS1 games which support/need disc swapping.
Any fix?

**Comment by xjsxjs197** [comment]
Fix the cdrom logic, this issue should be fixed.

**Comment by saulfabregwiivc** [comment]
Tested Driver 2 and Vib-Ribbon - this was fixed! Thanks very much ;)
