### ISSUE TITLE
[Question] Possibility to run the emulator on a different ISO?

### ISSUE THREAD

**Issue by Sonico98** [xjsxjs197/WiiSXRX_2022#164]
This would allow the use of xerpi's [FAKEMOTE](https://github.com/xerpi/fakemote) module, which would make it possible to play games using DS3 and DS4 controllers.

**Comment by xjsxjs197** [comment]
One long-term goal of WiiStation is to support HID controllers and nintendont. I hope to integrate the HID code into WiiStation instead of modifying IOS,but this is not an easy task and requires a long time.

**Comment by Sonico98** [comment]
Thanks, I was thinking that maybe using a different IOS could be easier to implement than integrating the HID code into WiiStation, but as you say, it would be better if it worked in the same way Nintendont does. Also, no hurries! What you're doing is already huge, thanks a lot!

**Comment by saulfabregwiivc** [comment]
You can try grabbing the WiiStation forwarder channel (i've made one in GBAtemp), edit it with CustomizeMii for edit the base IOS to load with the one you use for Fakemote, and see if that works.
