### ISSUE TITLE
Latest builds of WiiStation have several audio/music issues

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#168]
From: [rexus_pl](https://gbatemp.net/members/rexus_pl.590079/) in [GBAtemp](https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10300882)

Tested latest commits until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/0021dcc67f84b36a46359cbe03ffd95489e8eed1

Some games that used to play correctly their music now are acting like this:

**Vib-Ribbon** now the music sounds horrible.
**Worms Armageddon** has cracky music on menu (everything is fine during game) - I'm not sure, but it sounded good some time ago.

**Comment by xjsxjs197** [comment]
There seems to be an issue when starting from BIOS. If it's not booted from BIOS, it seems like there's no problem

**Comment by saulfabregwiivc** [comment]
About this issue:

The new builds seems to fix Vib-Ribbon music, but Worms Armageddon still has audio issues.

Anyways, i saw you talked in this issue https://github.com/notaz/pcsx_rearmed/issues/329 and i merged some changes from upstream PCSX-ReARMed in this branch: https://github.com/saulfabregwiivc/WiiStation/commits/pcsx-rearm-fixes-07122023

Could you please test this build for see if this still plays fine the music in Vib-Ribbon and other games after i merged those fixes?
Thanks ;)
[WiiStation_pcsx-rearm-fixes-07122023.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13607580/WiiStation_pcsx-rearm-fixes-07122023.zip)

**Comment by xjsxjs197** [comment]
@saulfabregwiivc 
The issue with Vib Ribbon has been fixed. It's because I added an additional check for cdr. Muted in cdrom. c. Just delete it and it will be fine. 
The problem with Worms Armageddon still exists.

**Comment by xjsxjs197** [comment]
Unfortunately, there is still a music issue on my Wii physical device...

**Comment by saulfabregwiivc** [comment]
closed as i think with later updates this was fixed. i will reopen this if not, but i think it's fine to close it.
