### ISSUE TITLE
Resolution options don't seem to change anything, mainly 240p

### ISSUE THREAD

**Issue by xonsuprimes** [xjsxjs197/WiiSXRX_2022#169]
Running through composite cables on an NTSC CRT, both "Interlaced" and "240p" are independently toggleable of one another and neither change the native resolution from 480i on the menu or in-game.

**Comment by xjsxjs197** [comment]
Please try this version and if the issue is fixed, please close it. 
[boot20231205.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13555891/boot20231205.zip)

**Comment by xonsuprimes** [comment]
Didn't work for me, still 480i on everything.

**Comment by xjsxjs197** [comment]
When the display information changes, especially when the height changes, switchToTVMode needs to be called. 
Try this new version and test it on the Dolphin emulator. I feel like it should work. 
[boot20231206.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13578025/boot20231206.zip)

**Comment by xonsuprimes** [comment]
Yup it's showing 240p now in game, just tested on both. Thanks a bunch, massively appreciate all the work you do.
