### ISSUE TITLE
Any chance for add Force NTSC option from Jokippo to the new SoftGPU?

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#171]
Hi there @xjsxjs197 

Thanks for ur hard work and also for the new SoftGPU plugin, but by the way, could you try adding this commit from @Jokippo for add an option for force NTSC video/mode to WiiStation?
https://github.com/Jokippo/WiiSXRX_2022240p/commit/9f1a2ab06523069970400c06e219c0971722bceb

However, it was made for the old P.E.Op.S. Soft GPU, but could you try adding that adapting to the new SoftGPU?

Thanks ;)

**Comment by xjsxjs197** [comment]
I tried to merge the logic of Force NTSC into the latest code, But there may be intermittent sounds, and it seems difficult to adjust them to a smooth state.

**Comment by saulfabregwiivc** [comment]
Btw, Jokippo already stated that some PAL games if forced to NTSC will run faster than intended...

**Comment by xjsxjs197** [comment]
The logic of Force NTSC has been merged into the main branch, and it seems that there is no problem now

**Comment by saulfabregwiivc** [comment]
Thank you @xjsxjs197 , btw i made a PR for rework the GPU timing suggested by notaz.
