### ISSUE TITLE
Click in "Execute Bios" on Settings, causes DSI exception.

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#178]
Like the title says, if you try to boot the BIOS using the button Execute BIOS, it causes an instant DSI exception (code dump) error.

Can you fix it? Thanks ;)

![image](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/4e5b6450-8fcc-4397-bcdf-19745d48c336)

**Comment by xjsxjs197** [comment]
The problem has been corrected.

**Comment by saulfabregwiivc** [comment]
Thanks for fixing it. :)

**Comment by saulfabregwiivc** [comment]
Fixed as of https://github.com/xjsxjs197/WiiSXRX_2022/commit/614fe7d2e219b92f56113e8a9c0b7102eba5ed62.
