### ISSUE TITLE
Trying to swap discs with Swap CD, causes the emulator to crash and return to the Wii Menu.

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#179]
Not sure what happened here or from which commit started this issue but now when you try to swap discs with the Swap CD button, when you return to the game with "Resume Game" after swapping the CDs, it makes the emulator to instantly crash and return to the Wii Menu.

Any clues? Any fix for this?

**Comment by saulfabregwiivc** [comment]
Commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/e4b274ef9dcb28ea8501b5912ac69a10ae60f076 fixed the crash/return to Wii Menu, but still the Swap CD function doesn't work.

Tried Driver 2, Vib-Ribbon, etc., and all games i've tested the games won't recognize the changed disc.
Vib-Ribbon stays at "Checking..."
Driver 2 doesn't detect the Disc 2

**Comment by xjsxjs197** [comment]
[WiiSXRX_Release20231226.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13771549/WiiSXRX_Release20231226.zip)
The version I built today, both Driver2 and ParasiteEve, can be swaped normally

**Comment by saulfabregwiivc** [comment]
Thanks for the build.

Tested again Driver 2 and Parasite Eve, they can swap discs normally.
Will test other games shortly.

Unfortunately Vib-Ribbon still struggles at "Checking..." screen after i swap CDs for custom tracks.
I will attach here a BIN/CUE with a custom track/song so you can try playing it on Vib-Ribbon with Swap CD and try to debug it.
(It worked fine on previous commits/releases, and it works fine on PCSX-ReARMed.)
https://www.mediafire.com/file/61p9ptftcgw955c/vibrimusic_nivirodiamond_BINCUE.zip/file

Question: could you try merging the piece of code "**ReloadCdromPlugin()**" from PCSX-ReARMed and apply the disc swap fix like emukidid done here in WiiSX?:
https://github.com/emukidid/pcsxgc/commit/a59dbae2942bcca9841193a65dec299c5555b030
Not sure if this will fix it, but i thought we have to try. (i tried merging that but i get a lot of compiler errors...)

**Comment by saulfabregwiivc** [comment]
Okay, seems sometimes the game don't take my swapped CDs and sometimes the game does. Weird.
(only tested Vib-Ribbon for now)

**Comment by xjsxjs197** [comment]
Let me try to modify it.

**Comment by xjsxjs197** [comment]
The code has been merged, and Vib Ribbon can also swap discs normally.

**Comment by saulfabregwiivc** [comment]
Thank you for your fix, it's working properly now.

By the way, Happy New Year 2024.

**Comment by xjsxjs197** [comment]
> By the way, Happy New Year 2024.
Happy New Year 2024. (^_^)
