### ISSUE TITLE
Loading save states does nothing.

### ISSUE THREAD

**Issue by oofingberg** [xjsxjs197/WiiSXRX_2022#19]
I tried making a save state and it said something among the lines of „save complete“ or something. After that i tried loading the save and it confirmed me that it did succed in doing that but when i resume the game im still at the same place. The save hast loaded

**Comment by saulfabregwiivc** [comment]
What game are you specifically trying to make/load savestates?

**Comment by oofingberg** [comment]
The FF7 retranslation disc 1

**Comment by saulfabregwiivc** [comment]
Sorry for late response
Where did you attempted to save the states/game savedata (from SD or USB)?

**Comment by oofingberg** [comment]
It should have been Sent from my iPhoneOn 11. Nov 2022, at 16:14, saulfabreg Wii VC Project ***@***.***> wrote:﻿
Sorry for late response
Where did you attempted to save the states/game savedata (from SD or USB)?

**Comment by saulfabregwiivc** [comment]
> It should have been Sent from my iPhoneOn 11. Nov 2022, at 16:14, saulfabreg Wii VC Project ***@***.***> wrote:﻿ Sorry for late response Where did you attempted to save the states/game savedata (from SD or USB)? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

what? your response was glitchy.

**Comment by oofingberg** [comment]
I think it was on my SD card and if i remember right its was on the ff7 retranslation. Sent from my iPhoneOn 12. Nov 2022, at 19:54, saulfabreg Wii VC Project ***@***.***> wrote:﻿

It should have been Sent from my iPhoneOn 11. Nov 2022, at 16:14, saulfabreg Wii VC Project @.> wrote:﻿ Sorry for late response Where did you attempted to save the states/game savedata (from SD or USB)? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

what? your response was glitchy.

**Comment by saulfabregwiivc** [comment]
make sure you have the following folders on the root of your SD card:

/wiisxrx/saves/
/wiisxrx/savestates/
