### ISSUE TITLE
Update to libchdr

### ISSUE THREAD

**Issue by malvarenga123** [xjsxjs197/WiiSXRX_2022#192]
Hi @xjsxjs197, it seems that v3.0 was released without updating libchdr (https://github.com/rtissera/libchdr/commit/26d27ca4903aaccd3ef41337b29bf5ecafb1f0ca) which brings Zstandard support to CHDs.
Would it be possible to update it so that Wiistation can read such files?

Edit: Also, you might want to take a look at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

**Comment by saulfabregwiivc** [comment]
recently i'm trying to bring ZStandard support for read CHDs with those format.
But it would take some time.

**Comment by saulfabregwiivc** [comment]
I have done the merge, btw needs more testing.

This PR https://github.com/xjsxjs197/WiiSXRX_2022/pull/202 might close this issue.
