### ISSUE TITLE
Going to Settings > Saves it crashes on code dump error

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#2]
![image](https://user-images.githubusercontent.com/66485640/175792748-74b80d0a-f859-4f60-8d14-fc6704aeb61f.png)

When you open the "Settings" section and then click on the "Saves" button, it just crashes (hangs) the Wii in code dump error (DSI exception).

Anyways, nice work with this mod, i'm testing still more PS1 games in it :)

**Comment by xjsxjs197** [comment]
A simple error occurred when modifying the menu. The value of NUM_FRAME_BUTTONS has been corrected.
