### ISSUE TITLE
artificial intelligence delaying

### ISSUE THREAD

**Issue by alexvitor** [xjsxjs197/WiiSXRX_2022#20]
Hello, how are you. I'm playing Brave heart, a tactical rpg game. when the cpu plays, it takes a long time for the artificial intelligence to decide what to do. making it take time. tiring.

**Comment by saulfabregwiivc** [comment]
Sorry i couldn't find the exact name of the game you're trying.

Can you share the title screen of the game or at least the full name of the game (not just "Brave heart" for avoid confusion between various games with the same name)?

**Comment by alexvitor** [comment]
Hello, how are you? sorry for that detail. brave heart slus_004.47, a detail that I forgot to mention that only your version opens this game and using bios(hle). thank

**Comment by saulfabregwiivc** [comment]
> 

I think you're referring to "Vandal Hearts" game? (i think since i googled SLUS-00447)
https://psxdatacenter.com/games/U/V/SLUS-00447.html

**Comment by alexvitor** [comment]
correct. that's it. a good game. I want to finish it, but each phase is 2 hours or more because of the cpu that takes a long time to make the move. and if i use the american bios the emulator crashes. thanks for helping.

**Comment by alexvitor** [comment]
correct. that's it. a good game. I want to finish it, but each phase is 2 hours or more because of the cpu that takes a long time to make the move. and if i use the american bios the emulator crashes. thanks for helping

**Comment by saulfabregwiivc** [comment]
> Author

okay.
Maybe @xjsxjs197 can take a look at this? I only contributed with language and readme updates.

**Comment by saulfabregwiivc** [comment]
> correct. that's it. a good game. I want to finish it, but each phase is 2 hours or more because of the cpu that takes a long time to make the move. and if i use the american bios the emulator crashes. thanks for helping.

okay.
Maybe @xjsxjs197 can take a look at this? I only contributed with language and readme updates.

**Comment by carnage702** [comment]
i downloaded the usa version and used usa ps1 bios and the AI takes like 2 seocnds to do its move, i dont think it has any delay tbh.

**Comment by alexvitor** [comment]
my version is american, and when i use usa bios, the emulator crashes. on nius wisx, the game opens even propagating from konami, then goes back to the homebrew channel.

**Comment by saulfabregwiivc** [comment]
> i downloaded the usa version and used usa ps1 bios and the AI takes like 2 seconds to do its move, i dont think it has any delay tbh.

What BIOS files you have on the wiisxrx/bios folder?
And what is the CRC of your SCPH1001.bin file you're using?
Also, can you share the settings you're using?

**Comment by carnage702** [comment]
> my version is american, and when i use usa bios, the emulator crashes. on nius wisx, the game opens even propagating from konami, then goes back to the homebrew channel.

maybe you got a bad iso then? i use ntsc iso with bios no problems using the original ps1 ntsc bios btw.

**Comment by alexvitor** [comment]
in the folder, I have 13 ps1 bios, is that why? I thought the emulator recognizes it automatically. I'll just leave the scph1001.bin to see if it works.

**Comment by alexvitor** [comment]
![bios wii](https://user-images.githubusercontent.com/107768666/184211667-ae30296a-9f2c-4bb1-bdfd-0dfbfa2344e3.png)

**Comment by carnage702** [comment]
nope they arent recognized automatically lol becuase there is no such things, games dont choose the bios, the bios is what the system has when it runs the games so no games chooses any bios at all,the emulator only reads 2 bios it reads any bios renamed to SCPH1001.BIN for usa games and the bios renamed SCPH1002.BIN for pal ones.

Also you need to se the bios locations on wiisxrx settings to sd/usb and then choose boot through bios.

if you renamed a pal bios to the ntsc name then that would give trouble same for the other way around, if you got the correct settings on wiisxrx  and the correct bios the game will boot normally if it doesnt then your iso is bad too.

**Comment by alexvitor** [comment]
OK. I will do this. I already replied if it worked. thanks

**Comment by saulfabregwiivc** [comment]
i could recommend getting your ISOs of PS1 from Redump. (Internet Archive is your friend)

**Comment by alexvitor** [comment]
I tested the bios, but it didn't work. the emulator crashes. I tested it in other games (xenoguers, alundra, valkirie profile, dino criss 1) and all the emulator crashes. only in bios(hle) they run well. another problem is also the save state, it saves the game, but when we load it to continue playing, it opens with the game locked

**Comment by carnage702** [comment]
> I tested the bios, but it didn't work. the emulator crashes. I tested it in other games (xenoguers, alundra, valkirie profile, dino criss 1) and all the emulator crashes. only in bios(hle) they run well. another problem is also the save state, it saves the game, but when we load it to continue playing, it opens with the game locked

then its an issue on your end, bios works perfectly fine for me hle is awful it makes the compatibility way lower, if you dont know how to use a bios i cant really help you, all there is to it is have the isos and bios on the same device be it usb or sd and the ps1 original bios being named SCPH1001.BIN and then choose the bios place on the wiisxrx settings sd/usb and save and then choose boot through bios to yes.

**Comment by saulfabregwiivc** [comment]
![image](https://user-images.githubusercontent.com/66485640/186045764-4ecaee49-e5cc-476e-925b-98e1aac5810f.png)

On Settings:
1. Choose to load BIOS from your SD or USB (depending of where did you store your BIOS).
2. Enable the "Boot through BIOS" option (by selecting Yes)
3. Save the settings and try to load the game.

**Comment by alexvitor** [comment]
this procedure that is in the photo, I did exactly that. so far everything is ok. but when I load the game for me to play, the emulator crashes. and another problem is that you are using dolphin. but i am playing on wii console. why your wiisx no problem

**Comment by carnage702** [comment]
> this procedure that is in the photo, I did exactly that. so far everything is ok. but when I load the game for me to play, the emulator crashes. and another problem is that you are using dolphin. but i am playing on wii console. why your wiisx no problem

I use both a Wii and wiiu and bios works fine for me.

**Comment by carnage702** [comment]
> this procedure that is in the photo, I did exactly that. so far everything is ok. but when I load the game for me to play, the emulator crashes. and another problem is that you are using dolphin. but i am playing on wii console. why your wiisx no problem

here i even made a video running the game on my wii so you can see im not lying, you probably have corrupt files or something if you cant even use regular bios, hle compatibility is way lower than the ps1 stock bios you should never use hle specially when making compatibility testing...
 check my video below
https://www.youtube.com/watch?v=GAhfVcRg8Xk

**Comment by alexvitor** [comment]
Hi everyone, everything fine. just wanted to inform you that the new version released recently has been fixed the artificial intelligence using bios hle. now it's normal. the only problem is that the emulator crashes when using the original bios. the emulator is progressing, congratulations.
