### ISSUE TITLE
[feature] audio interpolation, like actual ps1 hardware

### ISSUE THREAD

**Issue by therealteamplayer** [xjsxjs197/WiiSXRX_2022#200]
I think this issue has been brought up before so I figured I'd make an issue to track it. please lmk if this is a duplicate.

Real PS1 hardware, much like the SNES, applies gaussian interpolation to audio with low sample rates. This emulator currently does not implement that, which causes the audio to sound more "scratchy" than it should.

**Comment by xjsxjs197** [comment]
You can try this version, which was compiled specifically for this issue.  I didn't hear much difference, but it does feel like there are subtle differences.

[boot20240313.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/14580466/boot20240313.zip)

**Comment by saulfabregwiivc** [comment]
I know PCSX-ReARMed has the Gaussian interpolation sound option (set as **spu_config.iUseInterpolation=2**).

However, WiiStation has disabled this, even when the code for gaussian interpolation is there, it's just disabled/commented.
Maybe it's unstable for Wii, i guess? I don't know.

**Comment by xjsxjs197** [comment]
Firstly, it increases the amount of computation, which may have some impact on performance.  I don't know how much it will affect.  If there are no major issues, I would like to add it as an option to WiiStation.

**Comment by xjsxjs197** [comment]
This feature has become an option that can be enabled in the SPU settings
