### ISSUE TITLE
Some games have slowdowns that weren't present before, like CTR: Crash Team Racing.

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#209]
Not sure what happened here but it seems some games that had good or even full speed now they're running slow now?
I think it's because of the new video plugin but i'm not sure.

More noticeable in **CTR: Crash Team Racing (USA) (SCUS-94426)**, on some 3D games, and maybe also some 2D games? (Check this issue https://github.com/xjsxjs197/WiiSXRX_2022/issues/208).

**Also, it seems that some games have wrong FPS?** (61-62 FPS, what? isn't supposed to be 59.90 FPS or similar?)

**Comment by ghr89** [comment]
Hi saul
With interlaced mode on, does the game work normally? I haven't tested it yet, but a colleague told me it works perfectly.

**Comment by xjsxjs197** [comment]
> i have tested some games, and only some have the speed issues fixed.
> CTR: Crash Team Racing however still slows down in some parts of the game, sadly.

The choice of Dithering seems to have a significant impact on speed. If you choose None, the speed will be significantly better, but if you choose Default, it will be slower. Perhaps this is the reason

![image](https://github.com/xjsxjs197/WiiSXRX_2022/assets/31617363/fb221c3f-7ff2-4e97-be9d-f664411dc186)

**Comment by xjsxjs197** [comment]
Another possible reason is that in Ver1.0, each instruction ran at a clock speed of 2.0, and after Ver2.0, it ran at a clock speed of 1.75 (175/100).
If you feel that some games cannot run at full speed, you can try setting it to 200 in the cycle_multiplier_overrides section of database.c

**Comment by DenGueCB** [comment]
Hi, @xjsxjs197.

I've been playing "Xenogears" using version 3.2 of the emulator and I agree with the previous user; I've noticed a couple of things I'd like to share with you:

3D Performance: Compared to version 2.4, the frame rate drops are more noticeable, especially in gear battles and in city areas with a lot of polygons. This significantly affects the fluidity of the game.

2D Sprite Issue: The problem with vertical transparency lines cutting through 2D sprites during battles still persists. It's something that has been in previous versions and continues in 3.2.

I hope this information is helpful for polishing up these details. Thanks for your work on the emulator!

**Comment by xjsxjs197** [comment]
Recompiled a version using the old SoftGpu. If the occasional slow speed issue is resolved, the old Gpu will be added as an option

[WiiSXRX_Release.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/15385346/WiiSXRX_Release.zip)

**Comment by saulfabregwiivc** [comment]
> Recompiled a version using the old SoftGpu. If the occasional slow speed issue is resolved, the old Gpu will be added as an option
> 
> [WiiSXRX_Release.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/15385346/WiiSXRX_Release.zip)

Tested this and now it fixed the frame pacing issues with 60fps NTSC games, also there's no stutterings in Castlevania: Symphony of the Night anymore, works as fast as 2.4 and has the benefit of gaussian audio (thanks for this), and also scaling issues in 240p are also fixed here (tested with Chrono Cross)!

Only issue i've found here, is that the "Force NTSC" option is not working anymore? Cause i tested that mode with the new build and PAL games still run at 50 FPS, like it is disabled? Any fix for the Force NTSC option?

Thanks for your hard work.

**Comment by xjsxjs197** [comment]
By default, the old software rendering GPU plugin is used. Please try the latest compiled version
The control logic of Force NTSC has also been modified. If this issue is solved, let's temporarily close it. Another ticket for other issues
[boot.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/15493188/boot.zip)

**Comment by xjsxjs197** [comment]
This issue seems to have been resolved and is temporarily closed
