### ISSUE TITLE
Not able to use the Multitap option anymore since addition of HID controllers support?

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#222]
Not sure what changed here but since the addition of the HID controllers support, more specific in the **Settings > Input > Configure Input**, i can't choose (enable) Multitap option anymore, but only lets me to choose **None, Gamecube Pad, Wii Pad,** and **HID Pad**.

Could you bring back the option for enable Multitaps here? Thanks!

(it should let me choose between **None, Gamecube Pad, Wii Pad, HID Pad**, and **Multitap**.)

oh, and btw, before i forget, in the controllers connected to Multitaps, also add the option menu/button for use HID Pad!

**Comment by saulfabregwiivc** [comment]
Thanks, this brought back the Multitap option and it still works fine!

Btw, i know this could be useless since we can't connect more than one HID controller at the same time but it would be possible to add the option for use HID Pad in the Multitap input menus in at least one of the controller ports of the Multitaps?

![multitap menu](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/43f41082-6722-4148-8242-3257c28c895d)

**Comment by xjsxjs197** [comment]
> Btw, i know this could be useless since we can't connect more than one HID controller at the same time but it would be possible to add the option for use HID Pad in the Multitap input menus in at least one of the controller ports of the Multitaps?

Now, HID pads can be selected from the Multitap input menu.

**Comment by saulfabregwiivc** [comment]
Sorry for not closing this issue, but anyways thanks for reenabling the option for select Multitap. :)
