### ISSUE TITLE
Graphical issue in 240p mode on CRT TVs on versions v3.x and up.

### ISSUE THREAD

**Issue by Hyllian** [xjsxjs197/WiiSXRX_2022#223]
I realized that issue in Chrono Cross, when walking from down to up or vice-versa. CC's native resolution is 320x216 (not 240), maybe it's the problem. I took two photos to show:

See the text on WiiStation v2.4:
![photo1-WiiStation-v2 4](https://github.com/xjsxjs197/WiiSXRX_2022/assets/825708/cb62113f-fc08-4e5a-9ed3-c029c50ee78f)

Now on WiiStation v3.2 (lines duplicated in the fonts):
![photo1-WiiStation-v3 2](https://github.com/xjsxjs197/WiiSXRX_2022/assets/825708/556cacd3-2aa1-46d5-8817-50b8d40faac0)

Again WiiStation v2.4 (See the circles):
![photo2-WiiStation-v2 4](https://github.com/xjsxjs197/WiiSXRX_2022/assets/825708/24635d17-6f9b-4a3b-8f2e-155508314b50)

Now on WiiStation v3.2 (see the lines duplicated distorting the circles):
![photo2-WiiStation-v3 2](https://github.com/xjsxjs197/WiiSXRX_2022/assets/825708/82e4e884-1ee7-4da6-a502-7c24053e20f2)

These lines appear all over the screen when scrolling vertically the game, giving a general shimmering artifact. You can see that those lines are duplicated lines, like if the original 216 lines were upscaled to something like 224 or something.

I think it's an easy issue to solve as v2.4 has it correct.

Anyway, congrats for this port, besides that, it's the best version yet!

**Comment by xjsxjs197** [comment]
By default, the old software rendering GPU plugin is used. Please try the latest compiled version

[boot.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/15493188/boot.zip)

**Comment by Hyllian** [comment]
> By default, the old software rendering GPU plugin is used. Please try the latest compiled version
> 
> [boot.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/15493188/boot.zip)

It indeed fix the scaling issue. Thanks!
