### ISSUE TITLE
vigilante 8 and star wars demolition wrong fov?

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#24]
Both games seem to suffer from the same exact issues(same engine?), where a middle distance from your vehicle is totally untextured and white  vigilant 8 SLUS-00510 and Star wars demolition SLUS-01183
![IMG_20220902_025921](https://user-images.githubusercontent.com/12446178/188043503-6da85daa-578d-4aff-8f90-c63adc2e7283.jpg)
![IMG_20220902_025717](https://user-images.githubusercontent.com/12446178/188043508-437606c4-0de0-403b-ad2a-a1e811893baa.jpg)

**Comment by saulfabregwiivc** [comment]
are you using the official current release or the compiled build with latest commits?

**Comment by carnage702** [comment]
> are you using the official current release or the compiled build with latest commits?

the one you compilled but it doesnt matter, this games were like this even before cdda.

**Comment by carnage702** [comment]
with the latest update  star wars demolition now no longer plays even it goes crazy 
https://www.youtube.com/watch?v=-Fk2LD4ni-g

The game you fixed before that cutscenes played too fast Bugs bunny and taz time busters(SLES-02896) now  you cant walk either, you slide on the floor or dont move at all worked fine before.
https://www.youtube.com/shorts/4v3UJE5aYs4

**Comment by carnage702** [comment]
with latest update games went back to having the same gfx issues they have on the first post.

**Comment by xjsxjs197** [comment]
Although the code just submitted has slight image errors, I feel that it is basically displayed correctly.

**Comment by carnage702** [comment]
> Although the code just submitted has slight image errors, I feel that it is basically displayed correctly.

yeah only the first vigilant 8 has some small gfx errors on a distance depedning on the angle or something 
![IMG_20221110_192640](https://user-images.githubusercontent.com/12446178/201191985-5c1efa14-1dc9-4b2a-b8f0-eb6f72346ddf.jpg)
![IMG_20221110_192239](https://user-images.githubusercontent.com/12446178/201191990-900375ba-351d-405c-8a91-f16f07d2b464.jpg)
 but yeah its mostly done thanks alot for this.
