### ISSUE TITLE
Weird emulator crash at exit not present in earlier versions.

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#240]
From: [xunga](https://gbatemp.net/members/xunga.498149/) on [GBAtemp](https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10432682)

I noticed that if you save a separate configuration for a specific game and immediately exit the emulator, the emulator freezes and forces you to disconnect the console (the configuration file for the game is still generated correctly though). If after saving instead of exiting directly you go back to the game and then exit the emulator, you return to the Homebrew Channel normally.

[Disorarara](https://gbatemp.net/members/disorarara.314293/) ([see post](https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10432950)):

I can also confirm the earlier reports of emu crashing upon exit, though it isn't a terrible issue it is still bothersome to have to force turn off the wii instead of returning to HBC.

**Comment by xjsxjs197** [comment]
I have also found similar issues, and I am not sure if it is caused by HID's multithreading or other code issues. In the process of resolution

**Comment by xjsxjs197** [comment]
Fixed some logic when shutting down the system. I haven't had any similar issues locally recently, so I'm not entirely sure if this issue has been fixed
[boot.zip](https://github.com/user-attachments/files/15936683/boot.zip)

**Comment by saulfabregwiivc** [comment]
Can confirm the crashes at exit are now fixed, at least for me and another friend when we tested.
