### ISSUE TITLE
star wars episode 1 phantom menace missing model parts

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#25]
Character models have missing body parts Slus_00884
![IMG_20220902_030145](https://user-images.githubusercontent.com/12446178/188043834-0f8c4f01-4728-4bca-8600-d63b60bb563a.jpg)

**Comment by saulfabregwiivc** [comment]
are you using the official current release or the compiled build with latest commits?

**Comment by carnage702** [comment]
> are you using the official current release or the compiled build with latest commits?

latest you compiled.

**Comment by saulfabregwiivc** [comment]
@carnage702 
Could you test the build compiled from branch "pcsxRearmGte" of WiiSXRX_2022 for see if this solve the problem?
[WiiSXRX_2022_pcsxRearmGte_git_e43c64e9_06092022.zip.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9499649/WiiSXRX_2022_pcsxRearmGte_git_e43c64e9_06092022.zip.zip)

@xjsxjs197 recently merged some GTE code from PCSX-ReARMed.

**Comment by carnage702** [comment]
> @carnage702 Could you test the build compiled from branch "pcsxRearmGte" of WiiSXRX_2022 for see if this solve the problem? [WiiSXRX_2022_pcsxRearmGte_git_e43c64e9_06092022.zip.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9499649/WiiSXRX_2022_pcsxRearmGte_git_e43c64e9_06092022.zip.zip)
> 
> @xjsxjs197 recently merged some GTE code from PCSX-ReARMed.

i did and it does indeed fix this but i could only get ingame in intrepreter.

**Comment by carnage702** [comment]
Using the latest compiled version at the time of writing this, the game became much worse, now you can't see a thing sadly
![IMG_20221029_232917](https://user-images.githubusercontent.com/12446178/198854839-bb92fff9-08a5-4d77-80a0-5a2ab8fdda25.jpg)

**Comment by saulfabregwiivc** [comment]
> Using the latest compiled version at the time of writing this, the game became much worse, now you can't see a thing sadly ![IMG_20221029_232917](https://user-images.githubusercontent.com/12446178/198854839-bb92fff9-08a5-4d77-80a0-5a2ab8fdda25.jpg)

from what branch are you testing? here's another video of you that shows another test:
https://www.youtube.com/watch?v=-Fk2LD4ni-g

from what branch is the post of here, and from what branch is the video? :/

**Comment by carnage702** [comment]
> > Using the latest compiled version at the time of writing this, the game became much worse, now you can't see a thing sadly ![IMG_20221029_232917](https://user-images.githubusercontent.com/12446178/198854839-bb92fff9-08a5-4d77-80a0-5a2ab8fdda25.jpg)
> 
> from what branch are you testing? here's another video of you that shows another test: https://www.youtube.com/watch?v=-Fk2LD4ni-g
> 
> from what branch is the post of here, and from what branch is the video? :/

used your main branch on gbatemp compiled

**Comment by carnage702** [comment]
this game was fixed with latest update to gte, it works fine now played 2 levels thanks alot.
