### ISSUE TITLE
EA Sports Supercross 2000 freezes console when starting races in dynarec(intrepreter works)

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#27]
SLUS-01005 like the title says when you start a race the console freezes on dynarec core, on intrepreter it works fine albeit abit slower.

**Comment by xjsxjs197** [comment]
Special correction required, use interpreted instructions(LW), The game can run normally

**Comment by carnage702** [comment]
thank you, you are amazing.
