### ISSUE TITLE
longer loading times on some games

### ISSUE THREAD

**Issue by gamecubefan1990** [xjsxjs197/WiiSXRX_2022#29]
Can it be that some games have longer loading times on loading screens than usual?
For example, if you start a new game with Lego Island 2, I have much longer loading times than with Niuus' WiiSXRX v2.7.
If it is important, I always play my games in the Pal version because of the German language.
I have tested with the current WiiSXRX 2022 Version 2022 09 03.

**Comment by saulfabregwiivc** [comment]
@gamecube007

Recently @xjsxjs197 took a look at this, and looks like it's fixed at commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/d6c34e458e680c3c64c7aef305434ac1e72992e8.

Could you try using this build i've compiled with latest commits?
[WiiSXRX_2022_git_d6c34e45_04092022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9497047/WiiSXRX_2022_git_d6c34e45_04092022.zip)

Tell me your results.

**Comment by gamecube007** [comment]
Unfortunately, the loading times in loading screens do not show any change.
I used a stopwatch to measure the time on loading screen when I start a new game on Lego Island 2.

WiiSXRX from Niuus: 12 seconds
WiiSXRX 2022 from xjsxjs197: 35 seconds

**Comment by saulfabregwiivc** [comment]
@xjsxjs197, have you tested the games @gamecube007 is telling for see if there are still longer loading times?
Any chance for look closer at this issue and what's causing to have longer loading times in some games?

**Comment by xjsxjs197** [comment]
> @xjsxjs197, have you tested the games @gamecube007 is telling for see if there are still longer loading times?
> Any chance for look closer at this issue and what's causing to have longer loading times in some games?

I haven't looked at this problem yet. Let me study it later

**Comment by saulfabregwiivc** [comment]
@gamecube007

Here we go again...
@xjsxjs197 posted another possible fix for reduce loading times, and it was tested on some games.
Could you test this build i will attach?:
[WiiStation_main_git_a12c773f_29092022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9679892/WiiStation_main_git_a12c773f_29092022.zip)

Tell your results here.

**Comment by gamecube007** [comment]
The loading speed is a little better.
Here are my Results for two games

Lego Island 2 (German Pal Version) (start a new game)
WiiSXRX v2.7 from Niuus: 12 seconds
WiiSXRX 2022 from xjsxjs197: 35 seconds
New compiled Version from saulfabregwiivc: 26 seconds

Need for Speed III - Hot Pursuit (Pal Version) (load the Hometown course)
WiiSXRX v2.7 from Niuus: 8 seconds
WiiSXRX 2022 from xjsxjs197: 26 seconds
New compiled Version from saulfabregwiivc: 19 seconds

**Comment by xjsxjs197** [comment]
The latest version can already reduce the read time of Lego Island 2 to around 15 seconds. 
This issue has been modified to this extent and will not be fixed in the future, so close it
