### ISSUE TITLE
Some hiccups on CDDA audio (track may skip/repeat randomly)

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#32]
From: @niuus

Tested on: Mortal Kombat Trilogy

When the CDDA track changes or ends, the track may skip/repeat (kinda like a scratched CD). This happens randomly, so it works okay most of the time. This happened while in the Tower Ladder view, between rounds, Mode Selection screen, Press Start to Continue screen.

Using a build i've compiled with latest commits on main branch until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/fd473d5e2a978169f6dab0c47f291b071c899b58

**Comment by xjsxjs197** [comment]
Adjusting the return time of Seekp and Play instructions finally resolved this issue.
In fact, importing the latest pcsxRearm cdrom code can solve this problem, but it will introduce disc swapping and other issues, so it has not been resolved yet.
