### ISSUE TITLE
Improvements for Castlevania SOTN (Wii)

### ISSUE THREAD

**Issue by Codythedragonrude** [xjsxjs197/WiiSXRX_2022#37]
Was wondering if there was any ways to get a proper framerate out of castlevania symphony of the night on the program side of things?
right now it seems to run pretty bad 
I know the wii is pretty weak hardware wise but can anything be done to at least get close to 60fps?

**Comment by saulfabregwiivc** [comment]
That's what why you have the "Frameskip" option on Settings.
You can also get a Wii U for play PS1 games at nearly full speed xD

**Comment by carnage702** [comment]
> That's what why you have the "Frameskip" option on Settings. You can also get a Wii U for play PS1 games at nearly full speed xD

not nearly lol all ps1 games are full speed on wiiu with vwii overclock i havent found one that needs frameskip yet.

**Comment by jksherk** [comment]
> > That's what why you have the "Frameskip" option on Settings. You can also get a Wii U for play PS1 games at nearly full speed xD
> 
> not nearly lol all ps1 games are full speed on wiiu with vwii overclock i havent found one that needs frameskip yet.

Can you try Tekken3? I don't think tekken 3 will run at 60 fps

**Comment by xjsxjs197** [comment]
Use lightrec, now this game can run full speed.
