### ISSUE TITLE
Destruction Derby 2 freezes in Championship racers

### ISSUE THREAD

**Issue by ghr89** [xjsxjs197/WiiSXRX_2022#38]
Destruction arenas works fine, but race mode freezes or give dump code

**Comment by saulfabregwiivc** [comment]
@ghr89 

Could you test this build i've compiled from mainCounter branch ( https://github.com/xjsxjs197/WiiSXRX_2022/tree/mainCounter ) with the BIOS music fix ( https://github.com/xjsxjs197/WiiSXRX_2022/commit/757780eae118aaf2a6d09297444c89cd0a5aecba )for see if the game works in this build?
I will leave it here.

[WiiStation_mainCounter-BIOSmusic_git_ebf8508_11102022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9780075/WiiStation_mainCounter-BIOSmusic_git_ebf8508_11102022.zip)

**Comment by saulfabregwiivc** [comment]
Update: i have tested the game again with the build i posted, but still has these issues @ghr89 mentioned

**Comment by carnage702** [comment]
xjsxjs197 always perfers people to put the code for the game which is missing in this case its 
SLES-00299 pal
SIPS 60012 jap
SCUS-94350 usa

**Comment by ghr89** [comment]
@carnage702 thank's to post code game info

**Comment by xjsxjs197** [comment]
MainCounter branch can run normally, but main branch  has a problem, which may be a problem with Gte code
