### ISSUE TITLE
BIOS music not heard on latest commits from git e0f12173

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#39]
Check this commit: https://github.com/xjsxjs197/WiiSXRX_2022/commit/e0f12173d78df55eac325b8e99701ee32268fd57

Althrough this fixes some audio issues (like the one with Chrono Cross), now it makes the BIOS sound (music) to not be heard.
Can you check what's making the BIOS sound to not be heard?

**Comment by xjsxjs197** [comment]
There is a mistake in one unnecessary correction, and the original source is restored
