### ISSUE TITLE
(Xenogears) Wii "freezing" when checking memory cards at title screen

### ISSUE THREAD

**Issue by Jimtsu** [xjsxjs197/WiiSXRX_2022#40]
Hi !
Firstly, thank you for your work ! PS1 emulation on Wii is more and more comfy 👌

So, all is in the title.

In dynarec mode, you can't load a save but you can save in game.
In interpreter mode, accessing memory at title screen is possible but... then you have to play in interpreter mode and that's really not a good experience.
It's still possible to load a save in interpreter, then use a save state, switch to dynarec and load this state.
Otherwise, Xenogears run very well :)

Well, thanks in advance for the future updates (even if there isn't a possible fix for this game) ! 😁

**Comment by xjsxjs197** [comment]
Tell me the version or number of the game. I'll try to fix it

**Comment by Jimtsu** [comment]
It's the "USA" version of the game (I think there is only one), " SLUS-00664, SLUS-00669" (2 Discs).

Thanks ! 😁

**Comment by xjsxjs197** [comment]
Refer to PcsxReloaded code and add iCache code. This problem should be corrected.

**Comment by Jimtsu** [comment]
Oh ok, thank you ! 👌

**Comment by saulfabregwiivc** [comment]
@Jimtsu 
Could you please test this build i will post here?
This was compiled from main branch until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/109c5c13

[WiiStation_main_git_109c5c13_16102022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9811274/WiiStation_main_git_109c5c13_16102022.zip)

However, @xjsxjs197 states that needs to be tested not just with Xenogears, but also with all PS1 games that are working in this emulator for see if this commit (ICache addition) has an impact with compatibility.

**Comment by Jimtsu** [comment]
I just tested it and Xenogears is working fine now ! 😁

As for the other titles, I personally tried some games (FFVII, Breath of Fire III, Castlevania SOTN, Persona 1 & 2) and didn’t notice any problems.
I hope it will be the same with the entire catalogue.

Anyway, thank you for your work and for your time !
