### ISSUE TITLE
[Request] Read games from both usb

### ISSUE THREAD

**Issue by cjunisl** [xjsxjs197/WiiSXRX_2022#47]
I currently use the usb0 (bottom) exclusively for wii games and the usb1(top) for gamecube and roms. Would it be possible to read games from usb1 too?

**Comment by xjsxjs197** [comment]
I don't think so. Wii games need ntfs format, but other apps need fat32 format. 
You can try a USB stick with two partitions, fat32 format partition for gamecube and roms.
And ntfs format partition for  Wii games.

**Comment by carnage702** [comment]
> I don't think so. Wii games need ntfs format, but other apps need fat32 format. You can try a USB stick with two partitions, fat32 format partition for gamecube and roms. And ntfs format partition for Wii games.

Not really wii games be be readed from fat32, fat32 can be used for everything , you can split wii games bigger than 4gb and still play them splitted on usbloader gx, but yeah i dont think the wii can read 2 diferent usb devices at the same time and join the games on the list, that seems way too much work to implement and we dont even know if both is hdds are formatted the same, he is better off just get a big hdd like 1tb-2tb and format it all to fat32 and have everything on one hdd no need for 2 hdds.

**Comment by cjunisl** [comment]
I actually use 2 different devices formatted in fat32 on both ports on the usb loader gx and everything works fine, I just need to set the loader's ios to 222.

If I have the bottom usb port device formatted in ntfs and the top usb port device in fat32 the WiiSXRX will automatically read games from the top usb port.  

My suggestion for WiiStation is not to list psx games from both ports but to select in the settings on which port the emulator will list the games. This would be extremely helpful.

**Comment by carnage702** [comment]
> I actually use 2 different devices formatted in fat32 on both ports on the usb loader gx and everything works fine, I just need to set the loader's ios to 222.
> 
> If I have the bottom usb port device formatted in ntfs and the top usb port device in fat32 the WiiSXRX will automatically read games from the top usb port.
> 
> My suggestion for the WiiStation is not to list psx games from both ports at the same time, but to select in the settings which port the emulator will list the games on. That would be extremely helpful.

that would just add overhead to the program, first you would need to scan all usb ports then make a new menu saying which one to load the isos from, just seems unnecessary, no emulator or homebrew app that i know does this, just get a bigger hdd and loose the split system would be much better imo.
