### ISSUE TITLE
[CRITICAL BUG] System timing autoFix being broken since git 0f1eb823 [needs to be fixed before WiiStation 1.0 release]

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#48]
**IMPORTANT: This bug is CRITICAL and it must be fixed before the release of WiiStation 1.0 urgently**

@xjsxjs197 

Starting from commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/0f1eb8237012a19ea3ee237066c8ea25638a20f4 (in previous commits before this one the timing autoFix worked fine), the system timing autoFix (which fixes Vandal Hearts, Parasite Eve II, etc.) isn't working anymore, it seems that this commit broke it.

On my latest builds i've compiled since this commit, the games mentioned doesn't work anymore.

Any chance for fix this **critical issue** before you release the WiiStation 1.0, but without breaking anything? Thanks!

**Comment by saulfabregwiivc** [comment]
Update: I have tested the other autoFixes (pR3000A, GPU "Fake Busy States") and these still work fine on latest commits, only the broken autoFix is the system timing.

**Please consider fixing this before you release WiiStation 1.0, thanks ;)**

**Comment by xjsxjs197** [comment]
Let me fix it.

**Comment by saulfabregwiivc** [comment]
After some testing, both main and mainCounter branches suffers the exact same issue that the timing autoFix is being broken.

When you fix it, could you apply that fix in main and mainCounter too?

**Comment by xjsxjs197** [comment]
I didn't find any obvious problems locally, so I didn't notice this problem.
The code has been corrected. Please help to confirm whether the problem has been corrected

**Comment by xjsxjs197** [comment]
In addition, the difference between the two branches is the timer module. Now the timer module is consistent, so the mainCounter branch can be deleted

**Comment by saulfabregwiivc** [comment]
I compiled both main and mainCounter branches and seems that this bug has been solved.
Thank you @xjsxjs197, you're amazing :D

**Comment by saulfabregwiivc** [comment]
@xjsxjs197, shall i close this issue now it's solved? :)

**Comment by xjsxjs197** [comment]
This issue can be closed. ^_^

**Comment by saulfabregwiivc** [comment]
Thank you @xjsxjs197 , keep doing your great work!
