### ISSUE TITLE
[Request] Possibility to disable Bilinear Filter?

### ISSUE THREAD

**Issue by Maesejesus** [xjsxjs197/WiiSXRX_2022#49]
Would it be complicated to give the option? 

I don't mind if it's something to put into the xml as an argument, like Enhanced mGBA does with certain settings; if altering the menus to add such choice is too much work but the blurriness of Bilinear really is bothersome and getting rid of it would improve the picture significantly, to the point where it could be a good compromise until 240p support could be worked on as that will no doubt take a lot more effort and time... and headaches. 

Regardless of it can be done, thanks for your work on this new fork, it has been improving quite a lot in these last months!

**Comment by Ouaz** [comment]
I support this request too. It would make the image way crisper (mandatory in 2D games ^^), without impacting performances (AFAIK).

**Comment by Maesejesus** [comment]
I never got a response to this, unfortunately. Now that Wiistation uses lightrec and the performance and compatibility are even better than before taking out bilinear would be even more desired.

**Comment by therealteamplayer** [comment]
seconded - the bilinear filter looks very ugly and I'd reckon it should be turned off by default. if possible it'd be great to have display options similar to Snes9XRX and similar emulators - they allow for bilinear to be turned on and off, and for the image to fill the 4:3 frame while retaining equally spaced and sized pixels. With the newest improvements to this emulator, getting the image looking right would push PS1 emulation on the Wii over the edge from good to great.

**Comment by Ouaz** [comment]
>  and for the image to fill the 4:3 frame while retaining equally spaced and sized pixels.

Yes, I second this too, as the 4:3 image is slightly squished horizontally (or on the x-axis, circles become ovals in 4:3 - not on "force 16:9" setting as, then, this fixes the extra stretching caused by the anamorphic widescreen).

**Comment by ghr89** [comment]
the linear filter was finally removed, now it's waiting for someone to make a compilation

**Comment by Ouaz** [comment]
I was that but I'm not sure to understand the commit description:

> Not having much effect, it may also lead to other problems

Does it mean removing the linear filter has not much effect on the blurriness, or the linear filter itself didn't have much effect (weird statement, as it was blurry enough imo :D) ?

**Comment by xjsxjs197** [comment]
The previously modified code was based on snes9xgx and added. Actually, there doesn't seem to be any significant improvement before and after the modification. In order not to raise any other issues, this modification has been directly deleted.
