### ISSUE TITLE
Batman Beyond - Return of the Joker  Crash on boot

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#53]
Batman Beyond - Return of the Joker ntsc usa  SLUS-01207 crashes after the bios and never boots. there is also a pal version with gameid SLES-02902

Using the main git  dol compilled only afew hours ago.

**Comment by carnage702** [comment]
if you choose hle instead of bios the game will boot but it will eventually crash before reaching main menu.

**Comment by xjsxjs197** [comment]
The code has been corrected, and the local test has no problems.

**Comment by saulfabregwiivc** [comment]
@carnage702 
i've compiled a build until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/fb84d4819cfcd5640f7c35d8132b8c37f7392113

download and test this build
https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10005975

**Comment by carnage702** [comment]
Confirmed working, thanks  xjsxjs197  i wish we had someone like you doing wii64 updates too xD
