### ISSUE TITLE
sugestão controle

### ISSUE THREAD

**Issue by alexvitor** [xjsxjs197/WiiSXRX_2022#54]
Good Morning. first of all congratulations for your work. the emulator is very good. I don't know if you can post suggestions here. what is missing in these emulators is support for pc control (as it is in nintendont) would you be able to implement this feature in the next version?
thank you and congratulations.

**Comment by carnage702** [comment]
i think what you mean is getting hid controller support.

**Comment by alexvitor** [comment]
yes.

**Comment by xjsxjs197** [comment]
The work of supporting HID controllers is almost completed. If you want to add controllers beyond what nintendont supports, you need to add a new INI configuration file. The process should be as follows:
Connect your HID controller to the Wii, and then start HID_Test.dol (please modify it to boot. dol). If the controller is supported, you will see normal connection information and information when each button is pressed. 
Send me the information when each button is pressed, and I will create an INI file. 
You can refer to the information in this link:
https://gbatemp.net/threads/nintendont-custom-controller-configuration-file.633068/#post-10164777

[HID_Test.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/14756167/HID_Test.zip)
