### ISSUE TITLE
Star Wars: Dark Forces only works when using real BIOS and with "Boot Through Bios" in "No" on WiiStation 1.0 (if in "Yes" freezes at first LOADING screen)

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#56]
Both Dynarec and Interpreter the game "Star Wars: Dark Forces" hangs (freezes) at first loading screen.
The commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/ecd5288aff9678184e959f0579b0e0a066801019 looked promising but when me and @carnage702 tested it it still didn't fix that game, still freezes on every region.

Game IDs:
SLUS-00297 NTSC-U
SLPS-00685 NTSC-J
SLES-00585 PAL
SLES-00640 PAL (Italy)
SLES-00646 PAL (Spain)

**Comment by xjsxjs197** [comment]
It's really strange. I can run normally through Dolphin and Wii. Please see the screenshot below.
![ID-WiiSXRX_ReleaseStation1 0_2022-11-05_21-17-21](https://user-images.githubusercontent.com/31617363/200121981-28e3aea1-c4e9-4fed-90a1-8975dfbdf506.png)
![ID-WiiSXRX_ReleaseStation1 0_2022-11-05_21-18-12](https://user-images.githubusercontent.com/31617363/200121985-402cf544-86ad-4b79-af77-5b2090509bce.png)
![ID-WiiSXRX_ReleaseStation1 0_2022-11-05_21-18-20](https://user-images.githubusercontent.com/31617363/200121987-a0bd2bd3-0114-4b25-8c6f-46b560f7fae8.png)

**Comment by carnage702** [comment]
> It's really strange. I can run normally through Dolphin and Wii. Please see the screenshot below. ![ID-WiiSXRX_ReleaseStation1 0_2022-11-05_21-17-21](https://user-images.githubusercontent.com/31617363/200121981-28e3aea1-c4e9-4fed-90a1-8975dfbdf506.png) ![ID-WiiSXRX_ReleaseStation1 0_2022-11-05_21-18-12](https://user-images.githubusercontent.com/31617363/200121985-402cf544-86ad-4b79-af77-5b2090509bce.png) ![ID-WiiSXRX_ReleaseStation1 0_2022-11-05_21-18-20](https://user-images.githubusercontent.com/31617363/200121987-a0bd2bd3-0114-4b25-8c6f-46b560f7fae8.png)

that is the japanese version im guessing only japanese version worls pal SLES-00585 PAL or usa  SLUS-00297 NTSC-U do not run, did you tried any of this versions?

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 
After further testing, Star Wars: Dark Forces doesn't even pass the first LOADING screen on literally ANY region.
(Even NTSC-J release doesn't pass the first LOADING screen even with autoFix)

Tested using this release https://github.com/xjsxjs197/WiiSXRX_2022/releases/tag/WiiStation_Ver1.0
Not sure if you're using this version too? Or maybe another build that even we don't have access to?

Can you share your settings?

**Comment by xjsxjs197** [comment]
I see. If you start a game through Bios, this problem will occur. I usually don't start Bios, so I don't find this problem.
But why? We need to investigate...

**Comment by carnage702** [comment]
> I see. If you start a game through Bios, this problem will occur. I usually don't start Bios, so I don't find this problem. But why? We need to investigate...

you are right if you clock start with bios to no the game will play normaly, seems that something isnt being cleaned after the bios plays and passes to the game  and makes it crash or something.

**Comment by saulfabregwiivc** [comment]
> 

I can confirm @carnage702's issue.
@xjsxjs197 
Star Wars: Dark Forces with the autoFix works fine (sorry for my stupidity) but only works when i have the BIOS files (SCPH1001.bin) and turn the "Boot Through Bios" option to "No"...
If i have that option in "Yes" the game crashes on LOADING... screen...

Not sure what's going on... Seems something isn't cleaned after booting the BIOS?

**Comment by xjsxjs197** [comment]
Today's code fix finally fixed this issue, Mainly due to the imprecise logic of ADSR.
