### ISSUE TITLE
hot wheels turbo racing Physics dont work correctly in Dynarec

### ISSUE THREAD

**Issue by carnage702** [xjsxjs197/WiiSXRX_2022#57]
Like Walwii posted on gbatemp thread

Using wiistation 1.0.
I had felt a difference when playing hot wheels turbo racing and today I could see it.

When running the game with Dynarec, the fps is around 60 but strangely the car movements have reduced response. At the beginning of the "Road to Rustwell" track, there is a jump that the player's car does not complete.

If I switch to Interpreter, the fps drops to 35 but the game has the physics I remembered and in that jump, the car completes and falls on the track ahead. I put video of each case on youtube.

In Dynarec, the car spins crazy when crashing. Similar to when he started developing the code for this game to work. In Interpreter, when hitting he doesn't go crazy.

dynarec
https://www.youtube.com/watch?v=KIWN3Mi1YwY

Interpreter:
https://www.youtube.com/watch?v=yTydCdNmtUw

the jump and collision physics only work correctly in intrepreter not in dynarec.

**Comment by saulfabregwiivc** [comment]
Same thing happens to me too :P 

IDS:
USA: SLUS-00964
Europe: SLES-02198

**Comment by xjsxjs197** [comment]
Problem 1 should be solved.
Problem 2 is not clear whether it is resolved, please help to confirm.

**Comment by saulfabregwiivc** [comment]
I have compiled the latest code until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/8bfcd8fdb977a6b8a333d93fdea08ef0d19fb368 and looks like the game now works fine, in the track mentioned now the player can complete the jump.
Not sure how is the car physics though, i will leave a compiled build until that commit.

@carnage702 

[WiiStation_main_git_8bfcd8fd_09112022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9974350/WiiStation_main_git_8bfcd8fd_09112022.zip)

**Comment by WalterLeal** [comment]
thanks for the compiled build.  I'll try

**Comment by carnage702** [comment]
> I have compiled the latest code until git [8bfcd8f](https://github.com/xjsxjs197/WiiSXRX_2022/commit/8bfcd8fdb977a6b8a333d93fdea08ef0d19fb368) and looks like the game now works fine, in the track mentioned now the player can complete the jump. Not sure how is the car physics though, i will leave a compiled build until that commit.
> 
> @carnage702
> 
> [WiiStation_main_git_8bfcd8fd_09112022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9974350/WiiStation_main_git_8bfcd8fd_09112022.zip)

seems fine to me also saulfabre we are both idiots lol analogue mode does work perfectly, the game devs are retarded, do you know what they did to accelerate and break in analogue mode? second joystick... its right there on the loading screen

![Nova Imagem de Bitmap](https://user-images.githubusercontent.com/12446178/200928492-f185a890-b95d-4917-82cc-78559c05e8a1.png)


yes in analogue mode you need to keep the right analogue stick forward to accelerate and back to break, what stupid control scheme but we were dumber since we didnt read at all lol.

**Comment by WalterLeal** [comment]
> I have compiled the latest code until git [8bfcd8f](https://github.com/xjsxjs197/WiiSXRX_2022/commit/8bfcd8fdb977a6b8a333d93fdea08ef0d19fb368) and looks like the game now works fine, in the track mentioned now the player can complete the jump. Not sure how is the car physics though, i will leave a compiled build until that commit.
> 
> @carnage702
> 
> [WiiStation_main_git_8bfcd8fd_09112022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/9974350/WiiStation_main_git_8bfcd8fd_09112022.zip)

Work perfectly 🤩!!!
