### ISSUE TITLE
Possibility of a decent PS1 Multitap support on separated builds?

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#58]
Is there any chance of improve the PS1 Multitap support code of this fork of WiiSXR https://github.com/vmartinv/wiisxr which has PS1 Multitap support?

The PS1 Multitap allowed to a max of 4 players to be played in only one PS1 console, in compatible games (ex. Crash Team Racing, S.C.A.R.S., Captain Commando, Bomberman: Party Edition, Crash Bash, etc.)
I know WiiSXRX also has separated builds with PS1 Multitap support but only a few games can be really played with more than 2 players on both Multitap builds of WiiSXR and WiiSXRX.

Any chance for make most PS1 Multitap games to be played on WiiStation (even when on separated builds), maybe from that code of Multitap from that fork of WiiSXR or better from PCSX-ReARMed?

EDIT: Looking at these comments on https://github.com/vmartinv/wiisxr/commit/1d20c06762dca21e6fbc45b4c7e80627873ec689#comments
Something very neat is to having a database on the emulator that allows to enable Multitap on a specific player port depending of the CD-ROM ID (something like the autoFixes you have done).

**Comment by saulfabregwiivc** [comment]
Update:
In case you're interested, the RetroArch port of PCSX-ReARMed has this option for connect the PS1 Multitap to Port 1/Port 2, maybe you wanna check some of this code? :)
https://github.com/libretro/pcsx_rearmed

**Comment by niuus** [comment]
> Is there any chance of improve the PS1 Multitap support code of this fork of WiiSXR https://github.com/vmartinv/wiisxr which has PS1 Multitap support?
> 
> The PS1 Multitap allowed to a max of 4 players to be played in only one PS1 console, in compatible games (ex. Crash Team Racing, S.C.A.R.S., Captain Commando, Bomberman: Party Edition, Crash Bash, etc.) I know WiiSXRX also has separated builds with PS1 Multitap support but only a few games can be really played with more than 2 players on both Multitap builds of WiiSXR and WiiSXRX.
> 
> Any chance for make most PS1 Multitap games to be played on WiiStation (even when on separated builds), maybe from that code of Multitap from that fork of WiiSXR or better from PCSX-ReARMed?
> 
> EDIT: Looking at these comments on [vmartinv/wiisxr@1d20c06#comments](https://github.com/vmartinv/wiisxr/commit/1d20c06762dca21e6fbc45b4c7e80627873ec689#comments) Something very neat is to having a database on the emulator that allows to enable Multitap on a specific player port depending of the CD-ROM ID (something like the autoFixes you have done).

Did you try to implement it? You said you were going to review it last december.

**Comment by xjsxjs197** [comment]
> Did you try to implement it? You said you were going to review it last december.

I haven't seen it yet. I will start this thing after a period of time .

**Comment by niuus** [comment]
> > Did you try to implement it? You said you were going to review it last december.
> 
> I haven't seen it yet. I will start this thing after a period of time .

I meant saulfabre, not you. This is the first time I see you addressing the peripheral.

**Comment by saulfabregwiivc** [comment]
> > > Did you try to implement it? You said you were going to review it last december.
> > 
> > I haven't seen it yet. I will start this thing after a period of time .
> 
> I meant saulfabre, not you. This is the first time I see you addressing the peripheral.

Yeah I attempted to integrate the code of multitap from vmartinv's repo and while this works fine, it works only on a (very) few games. My goal (and dream) is to play every possible PS1 Multitap game on WiiSXRX / WiiStation, or at least the Multitap can be connected to Port 2 and not just Port 1.

**Comment by namenamenam** [comment]
> a max of 4 players
If a multitap is connected to both ports at once, the upper limit is raised from 5 to 8, not 4. Maybe that could be supported also, with a mix of Classic controllers and GameCube controllers.

**Comment by saulfabregwiivc** [comment]
> > a max of 4 players
> > If a multitap is connected to both ports at once, the upper limit is raised from 5 to 8, not 4. Maybe that could be supported also, with a mix of Classic controllers and GameCube controllers.

But what about Wii Family Edition, Wii Mini, and Wii U? These doesn't have GameCube ports...

**Comment by namenamenam** [comment]
I know that, it’s just an idea. Maybe LAN play across multiple Wii consoles
could be a workaround, but that seems unlikely--
*this is my signature, indicating the end*
