### ISSUE TITLE
Can't use/run PS1 BIOS from USB drive on WiiStation (SD card works)

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#59]
From: [Zorg1996](https://gbatemp.net/members/zorg1996.496980/) on [GBAtemp](https://gbatemp.net/threads/wiisxrx_2022-another-fork-of-wiisxrx-released.614405/post-9987908)

I ran into a problem, I can't run the PS1 BIOS when on USB, and I get this screen of ISI exception (see picture below), and even if I force it to use the BIOS from USB by editing the settingsRX2022.cfg configuration file, on startup it gives me a black screen and an annoying beeping sound. (In the SD card it goes to 100%). I hope it can be solved.
Thanks for this great emulator.
PS: the games can run fine on USB, but if I want them to run with the BIOS from USB that problem happens.

![image](https://user-images.githubusercontent.com/66485640/200677817-1c7aa36d-56ca-4fa5-8cbc-8ec44b91a37c.png)

**Comment by xjsxjs197** [comment]
The problem should be solved

**Comment by saulfabregwiivc** [comment]
That fixed the problem, thank you so much! :D
