### ISSUE TITLE
Regression bug: Final Fantasy VII (NTSC-U) [SCUS-94163]

### ISSUE THREAD

**Issue by niuus** [xjsxjs197/WiiSXRX_2022#62]
**Final Fantasy VII (NTSC-U) [SCUS-94163]**

* Problem:
Battle cursor is glitched again, and game battles suffer from prolonged freezes when using Magic.

* How to recreate it:
Get into a battle where you have to fight at least 3 enemies, preferably two Soldiers and a machine gun robot. Pick Cloud's Magic (Blizzard / Thunder), and maintain the cursor over any enemy. Game will freeze for 7 seconds periods. This keeps happening later in the game, with other characters, during bosses, etc.

It's been happening since [this commit](https://github.com/xjsxjs197/WiiSXRX_2022/commit/bf10d88aee42c23560a08a0dad1f23ecaf25ed88) and up to this [recent commit](https://github.com/xjsxjs197/WiiSXRX_2022/commit/a351a19837ef23a89271cda4a237999437c327b3) so far.

I uploaded a [MC](https://anonfiles.com/u9E7O3Gdyf/SCUS94163_zip) to quickly get to the bug. Just walk around until a random battle begins.

**Comment by xjsxjs197** [comment]
This is the effect of [GPU 'Fake Busy States' hack]'s correction. 
It has been readjusted, so as not to affect other logic.

**Comment by saulfabregwiivc** [comment]
@niuus 

Could you test this build i've compiled until git https://github.com/xjsxjs197/WiiSXRX_2022/commit/747fa61dc949698911d53e3eb80959f0620562b5 i've posted in GBAtemp?
https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-9994821

**Comment by niuus** [comment]
> This is the effect of [GPU 'Fake Busy States' hack]'s correction. It has been readjusted, so as not to affect other logic.

Fixed with [747fa61](https://github.com/xjsxjs197/WiiSXRX_2022/commit/747fa61dc949698911d53e3eb80959f0620562b5). Nice work.
