### ISSUE TITLE
Vib-Ribbon levels playing earraping static audio instead of music

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#67]
Like the title says both versions of Vib-Ribbon when playing the levels instead of the music of the game, plays a earraping (noisy) static audio.

IDs:
Europe:
* SCES-02873

Japan:
* SCPS-18012
* SCPS-45469
* SCPS-91213 (for PlayStation The Best rerelease)
* SCPS-91308 (for PSone Books rerelease)

Suggestion: maybe apply an autoFix for fix this game's issue? Maybe pR3000A or CDDA? I'm not sure lol

**Comment by saulfabregwiivc** [comment]
Update:
@xjsxjs197 

After a little research, looks like Vib-Ribbon for be able to listen fine to the audio in levels the "Reverb" effect needs to be enabled on SPU (what i read:
https://www.reddit.com/r/RG350/comments/geqx1u/vibribbon_eu_the_unsolved_mystery/ )

Could you try making an autoFix for enable "reverb effect" in all these game IDs of Vib-Ribbon i've mentioned?

**Comment by saulfabregwiivc** [comment]
More info i've checked...
on this fork of PCSX-Reloaded there is some code made for Vib-Ribbon, could you please check?
https://github.com/gameblabla/pcsxr/blob/6484236cb0281e8040ff6c8078c87899a3407534/pcsxr/libpcsxcore/cdrom.c

I know that the CDDA part of CDROM of PCSX-ReARMed (and possibly Reloaded) isn't merged but i think this could fix this issue, who knows.

**Comment by xjsxjs197** [comment]
> I know that the CDDA part of CDROM of PCSX-ReARMed (and possibly Reloaded) isn't merged but i think this could fix this issue, who knows.

I have seen relevant codes before. It seems that cdrDecodedBufferInterrupt has no place to call, although CDRDBUF_ INT will trigger cdrDecodedBufferInterrupt, but there is always no entry, triggering CDRDBUF_ INT.
Where did I get it wrong?

**Comment by xjsxjs197** [comment]
> Could you try making an autoFix for enable "reverb effect" in all these game IDs of Vib-Ribbon i've mentioned?

Let me take a look at this.

**Comment by saulfabregwiivc** [comment]
Interestly, the PS1 BIOS also uses the reverb effect from SPU, which it may explain why the BIOS sound in WiiSX/R/RX/WiiStation sounds a bit different than i was acostumbrated to hear on PS1 original hardware.

Here's some differences:
No reverb (echo): https://www.youtube.com/watch?v=ads7KCkdJxM
With reverb (echo): https://www.youtube.com/watch?v=ekqYhP8PhMg

**Comment by saulfabregwiivc** [comment]
Fixed on upcoming Lightrec implementation on WiiStation at git https://github.com/xjsxjs197/WiiSXRX_2022/commit/ea98f831860034bc41f0f583eb456d05248c5b48

**Comment by saulfabregwiivc** [comment]
It still hangs at LOADING screen on further test (my bad, i confused with latest WiiSX).

**Comment by saulfabregwiivc** [comment]
I've left you some relevant info about this issue (and some info about latest WiiSX) in a PM on GBAtemp you sent me.

**Comment by xjsxjs197** [comment]
The music can finally play normally, it was a Big Endian issue.
I'm not sure if there are other similar games that write cdData into Reverb.

**Comment by saulfabregwiivc** [comment]
Thank you, another game is perfect now.

Vib-Ribbon is one of my favorite PS1 games, and now can be played fine on Wii :)
