### ISSUE TITLE
Final Fantasy 7 issues

### ISSUE THREAD

**Issue by Fylexio** [xjsxjs197/WiiSXRX_2022#70]
The cursor texture is gliched in battles and the game freezes when aiming with magic at the first boss and also some other enemys.
This problem does not occur in WiiSXRX.

**Comment by carnage702** [comment]
> The cursor texture is gliched in battles and the game freezes when aiming with magic at the first boss and also some other enemys. This problem does not occur in WiiSXRX.
[WiiStation_main_git_fb84d48_22112022.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/10203279/WiiStation_main_git_fb84d48_22112022.zip)

tryed the latest nightly tht was compiled from here?

**Comment by Fylexio** [comment]
Homebrew launcher does not recognize the file you sent me. Am I doing something wrong?

**Comment by carnage702** [comment]
> Homebrew launcher does not recognize the file you sent me. Am I doing something wrong?

Obviously you have to rename it to boot.dol and replace it ... Have you never used Wii homebrew?...

**Comment by Fylexio** [comment]
Okay it works now. I did rename it correctly but apparently I did something wrong or my linux distro didn't like my SD card.
The cursor texture seems to be fixed in the nightly build.

**Comment by Fylexio** [comment]
And the freeze also doesn't happen anymore.
