### ISSUE TITLE
Having problems booting games

### ISSUE THREAD

**Issue by Andrewyato** [xjsxjs197/WiiSXRX_2022#75]
Hi, I'm using this emulator with the homebrew of  the virtual wii but when i boot the game (in this case castlevania sotn) it boots the bios and it seems like its going to start but then i stay in the blue section where i can choose the memory card or go to the cd player, please if you know how to help me reply because i really eanted to play this game

**Comment by saulfabregwiivc** [comment]
Your PS1 games needs a CUE file each for be able to run.
I bet your games doesn't have a CUE file, so they can't run on WiiStation.
Try making a CUE file for your games by mounting it with DAEMON Tools Lite and making a single BIN/CUE with ImgBurn, or redownload your games.

**Comment by Andrewyato** [comment]
Ok i will try, thank you :)

**Comment by Andrewyato** [comment]
wait, how do i do this things? i never did this type of thing im sorry

**Comment by carnage702** [comment]
> wait, how do i do this things? i never did this type of thing im sorry

you can use cue generator online 
http://cuegenerator.teriffy.cz/

**Comment by Andrewyato** [comment]
ok i created the cue, now?

**Comment by carnage702** [comment]
> ok i created the cue, now?

cue must be named  in the same folder

example 
sd:wiisxrx/isos/metal gear solid/metal.iso
sd:wiisxrx/isos/metal gear solid/metal.cue

**Comment by Andrewyato** [comment]
now it works, thank you for the help :)
now i can finally play castlevania sotn

**Comment by saulfabregwiivc** [comment]
You're welcome... pls consider closing this issue ;)
