### ISSUE TITLE
PAL (European) BIOS sound (music) problems

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#85]
From: [Zorg07](https://gbatemp.net/members/zorg07.496980/) on [GBAtemp](https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10140417)

Excellent update, I saw that several games that required frameskip now no longer need it, for example Castlevania SOTN, but other games like Tekken 3 still require this option, now I have a problem is that the PAL bios sound like a damaged radio at the beginning, This happens with games like Dino Crisis (also in the initial part when you press START, you keep listening), other games that also happen were with Parasite Eve 2, to mention perhaps in other PAL games they precede the same, in the previous version that didn't happen, well I was aware of the latest builds of version 1.0, and it didn't happen either. I hope it can be solved :)

**Comment by xjsxjs197** [comment]
2.0 code can only use SCPH1001, The modified code, PAL standard game, can automatically load SCPH1002 or SCPH5502.
The sound should be normal now.
Byt the way, My local Dino Crisis (European) cannot run...

**Comment by gamecubefan1990** [comment]
> Byt the way, My local Dino Crisis (European) cannot run...

My Dino Crisis 1 (PAL) game cannot run on WiiStation too.
I think it has to do with the LibCrypt protection that used on some European PAL Games.
All PAL Games i test that use LibCrypt protection dont run or hangs on WiiStation.

**Comment by saulfabregwiivc** [comment]
@xjsxjs197
With this new commit, it still has BIOS sound problems on PAL games.

> Edit: Ok, that was my mistake, if you use the program SBITools to convert the .sbi file to a .sub file, Pal protected games work on WiiStation.
@gamecubefan1990 
Where you get the .sbi files for the games?

**Comment by gamecubefan1990** [comment]
> @gamecubefan1990 Where you get the .sbi files for the games?

You find all PAL SBI files on redump.org under the category Downloads.

Alternatively you can download LSD Patches.
When you download the program SBITools from github there are LSD Patches included.
You must only convert this LSD Patches to .sub file then PAL Protected Games run on WiiStation.
I tested the PAL Version from Dino Crisis 1, Crash Bash, Crash Team Racing and they all work with this patches, without these Patches the games hangs on loading screens or do not start.
