### ISSUE TITLE
Gran Turismo now stays on a black screen shortly after starting

### ISSUE THREAD

**Issue by xjsxjs197** [xjsxjs197/WiiSXRX_2022#86]
From: [Zorg07](https://gbatemp.net/members/zorg07.496980/) on [GBAtemp](https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10140417)

Gran Turismo now stays on a black screen shortly after starting, previously this did not happen. :(
It happens to me in the US version.

**Comment by saulfabregwiivc** [comment]
Interestly it doesn't happen on latest WiiSX Beta 3.0, here: https://github.com/emukidid/pcsxgc/releases

**Comment by xjsxjs197** [comment]
Using the latest devkitPPC and libogc2 compilation can solve this problem

**Comment by saulfabregwiivc** [comment]
Let me see, i will compile it later with latest devkitPPC/libOGC2.
PD: I made two pull requests for correct/improve info about libOGC2

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 it's not compiling properly with libOGC2, i will explain the problem here:
https://github.com/xjsxjs197/WiiSXRX_2022/pull/89

**Comment by saulfabregwiivc** [comment]
After a brief tests, the game Gran Turismo 1 (USA) it's fixed, so this issue can be closed:

![image](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/7d5bf751-8cf2-4055-8b9c-c93a83dff573)
