### ISSUE TITLE
Any chance for have 240p support?

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#9]
Is there any chance for make WiiSXRX_2022 have native 240p resolution, like the original PlayStation had?

**Comment by xjsxjs197** [comment]
Sorry, this requirement is not easy to implement in a short time. Now the main energy is to solve the compatibility problem

**Comment by saulfabregwiivc** [comment]
That's okay, i most prefer that WiiSXRX_2022 have better compatibility (and maybe speed) rather than having native resolution.

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 BTW, recently an user called Jokippo made some changes to add 240p support to WiiStation:
https://github.com/Jokippo/WiiSXRX_2022240p/releases/tag/v2.4-240p

The author however states that it only was tested on PAL and PAL60 TVs, and both work.
Needs some testing on NTSC TVs.

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 the user Jokippo made some changes and now the resolution switching to 240p is more stable, now it's fully working on NTSC, PAL, PAL60 and MPAL TVs.
https://github.com/Jokippo/WiiSXRX_2022240p/releases/tag/v2.4-240pV2

If you're interested, you can merge his changes for achieve one of your goals of having native 240p support.
Code: https://github.com/Jokippo/WiiSXRX_2022240p/tree/main

**Comment by xjsxjs197** [comment]
The revised content for 240P has been merged into WiiStation.
