### ISSUE TITLE
Weird crash on Vib-Ribbon after passing the entire intro (if skipped the game works fine)

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#91]
As the title says the game Vib-Ribbon all versions of the game (PAL or NTSC-J) if I let all the whole game intro to be played before eventually jumps to the title screen automatically, when I select "GAME" the game crashes at "LOADING" screen.

Strangely, this doesn't happen if you skip intro and select "GAME", which here works fine if you skip intro with START or X (B in my Wii Classic Controller) button.

**Comment by xjsxjs197** [comment]
Apart from version 2.0, do subsequent code modifications also result in error codes when compiling different versions? I have been using a locally compiled version and have not encountered any issues on Dolphin. However, previous versions did indeed experience similar problems on the Wii, leading to system crashes. You can try the latest version I have compiled.

[WiiSXRX_Release20230601.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/11621278/WiiSXRX_Release20230601.zip)

**Comment by saulfabregwiivc** [comment]
Tested this build you sent me and seems the crash on LOADING screen after letting the game play the entire intro doesn't occur anymore.
I'm not clear if this is occured by the compiler, some code, the version of Lightrec used by WiiStation, or something else? I don't know.

**Comment by xjsxjs197** [comment]
Give it a try after recompiling with the latest code. Additionally, I've noticed an interesting compilation phenomenon: sometimes when there are reverb sound issues, performing a "Clean" first and then doing a complete recompilation resolves the problem.

**Comment by saulfabregwiivc** [comment]
> Give it a try after recompiling with the latest code. Additionally, I've noticed an interesting compilation phenomenon: sometimes when there are reverb sound issues, performing a "Clean" first and then doing a complete recompilation resolves the problem.

Thanks for your tip.
I first ran make clean, then make Wii_Release and when i loaded Vib-Ribbon again, the crash is gone.
