### ISSUE TITLE
Vib-Ribbon (and other PS1 games) won't take my BIN/CUEs of music CDs (BIOS however takes them)

### ISSUE THREAD

**Issue by saulfabregwiivc** [xjsxjs197/WiiSXRX_2022#92]
Like the title says the game Vib-Ribbon (and possibly some more other PS1 games which support ejecting the game disc for insert an Audio CD for play their own music, ex. Ridge Racer Revolution) doesn't detect my BIN/CUEs of my custom music.

In the case of Vib-Ribbon, after used "Swap CD" for change to my music ISO, and when i return to the game, it stays at "Checking..." screen and it doesn't recognize my audio CD BIN/CUE.
Don't know about other PS1 games with said feature though.

However, when I boot the BIOS (Execute Bios) and then swap the CD with the same music CD BIN/CUE, it recognizes and plays fine.

On latest PCSX-ReARMed this same music CD BIN/CUE gets detected and plays fine.

Do you have idea what's the issue there?

PS: I will send you my music CD BIN/CUE which i know it works on PCSX-ReARMed with Vib-Ribbon, and on WiiStation with the BIOS CD Player.
https://www.mediafire.com/file/5my4rlo3kfabycc/MusicCD_NIVIRO_Diamond_NCS_PSX.zip/file

**Comment by xjsxjs197** [comment]
>Do you have idea what's the issue there?
I don't know the specific reason, I'll take some time to solve it later.

**Comment by saulfabregwiivc** [comment]
Tested with new commits of today but still can't detect the BIN/CUE of my music CD.

In case you're interested: PCSX-ReARMed also takes BIN/CUEs of Mixed Mode CDs, which usually are music CDs.

These are my results when trying to load that same music CD BIN/CUE i posted earlier:

**Vib-Ribbon:**
after swapping the CD to the music CD (Mixed Mode CD), it just stays at "Checking..."

![vib_checking](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/cb2f3b04-a18a-467a-bd9a-b8bf24f698b0)

**Ridge Racer Revolution:**
after swapping the CD to the music CD (Mixed Mode CD), it doesn't play the music contained in the swapped CD.

![rrr](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/930b464d-0658-4dd1-bc0a-227f7e833104)

**BIOS CD Player:**
after swapping the CD to the music CD (Mixed Mode CD), it recognizes and plays fine the song(s) included there.

![bios_cd_player](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/831765da-1d43-427e-9023-a865e49d70c2)

Still asking what's the issue there why BIOS CD Player detects the Mixed Mode CD BIN/CUEs but games doesn't on WiiStation (PCSX-ReARMed work though).

**Comment by saulfabregwiivc** [comment]
Fixed as of https://github.com/xjsxjs197/WiiSXRX_2022/commit/4b40658aa2d8112093b9a62769b5097a6dd37022.

But, only issue i've found is those audio hiccups, and sometimes the emulator stops the music and replays it again from some miliseconds early before it eventually plays from the point where music stopped.

Ridge Racer Revolution: plays the music contained on the music CD in any moment (ex., on intro)
![rrr_ridgemusic](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/1cdc80f8-06b7-403c-acda-b5b5d8b4c6f3)

Vib-Ribbon: gets past the "Checking..." screen and lets me choose the track and after selected, it plays fine.
![vibri_music](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/6d46ffed-9437-43bc-bc94-578a993049bc)

**Comment by saulfabregwiivc** [comment]
@xjsxjs197 

As i explained, your latest commit fixed Mixed Mode CDs (can be played fine on PS1 games now), but when they're read, they have CD read stops for a while and then reload them again, like if these were scratched CDs (though they actually isn't).

I explained this issue here on GBAtemp: https://gbatemp.net/threads/wiistation-another-fork-of-wiisxrx-released.614405/post-10187189
