### ISSUE TITLE
Beyond the Beyond: "New Journey" loops to intro

### ISSUE THREAD

**Issue by eku** [xjsxjs197/WiiSXRX_2022#93]
When pressing `New journey` to start the game it restarts to the intro sequence.

I'm running the USA version of the game on WiiStation 2.0 with autoboot through WiiFlow Lite. I guess you know how to get the game for testing.

If more information is needed or you want me to test something, please feel free.

**Comment by xjsxjs197** [comment]
Pressing the X button should allow you to enter the game normally. Pressing the circle button is the phenomenon you mentioned, and this should not be a problem

**Comment by saulfabregwiivc** [comment]
Circle button (O) in most games is for return to the previous menu...
X button in most games is for confirm a selection...
