### ISSUE TITLE
Chrono Cross (USA): Disc swap hangs

### ISSUE THREAD

**Issue by eku** [xjsxjs197/WiiSXRX_2022#95]
Even when I start the game with disc `1` after intro and pressing `start` it asks to insert disc `1`.

Selecting the`cue` of the first disc and pressing `Resume Game` locks the emulation. The emulator stops spinning the PS1 logo in the upper right corner but GUI is visible. Cursor keys are inactive, only the WiiMote `Home? button brings life in the emulator.

I'm pretty sure this worked at the very beginning of this fork from `WiiSX RX`.

If more information is needed or you want me to test something, please feel free.

**Comment by saulfabregwiivc** [comment]
You're doing the disc swap wrong.
For swap a disc, you return to the emulator menu, select "Current ISO", select "Swap CD", then load the disc you want to swap to and when it says "Swapped CD", return to the game with "Resume Game".
Let me know if it works :)

**Comment by eku** [comment]
> You're doing the disc swap wrong.

Please excuse me if I did not express myself exactly. But I acted exactly as you describe.

Both discs run fine when startet in non-autoboot mode from the `Load Disc` menu. So I guess the CUEs are correct.

I noticed something else strange. I start the game through `WiiFlow Lite`. The arguments for WiiStation are
```
app argument: usb:/wiisxrx/isos/Chrono Cross
app argument: Chrono Cross (USA) (Disc 1).bin
```
but WiiStation uses `Chrono Cross (USA) (Disc 2).cue`.  This is also the case with other multi-disc games when they are launched via WiiFlow. Very strange.

If you would like to test with my version of the game, use `site:archive.org [REDUMP] Disc Image Collection`  with your favourite search engine.

**Comment by xjsxjs197** [comment]
Please try using the latest version, At least this version fixes the issue of MGS disc swapping.
[WiiStationV2.3.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/11777972/WiiStationV2.3.zip)

**Comment by eku** [comment]
Thanks @xjsxjs197 , this fixes the disk-swap problem for this game. 

I am still confused as to why WiiStation chooses the wrong CD first. Should I open a diffent ticket?

**Comment by xjsxjs197** [comment]
If there are any other issues, please pick up the ticket again. This ticket will be closed.
