### ISSUE TITLE
FF IX (German/SLES02967) does not start

### ISSUE THREAD

**Issue by eku** [xjsxjs197/WiiSXRX_2022#96]
When starting the first of four discs of FF IX the screen goes black and stays black. Nothing happend even after minutes.

However the emulator menu can still be reached via the Wii Remote.

If more information is needed or you want me to test something, please feel free.

**Comment by carnage702** [comment]
just making sure do you have all your cue files correctly made? since they need to be correct.

**Comment by saulfabregwiivc** [comment]
Like @carnage702 said, mainly these issues are caused by bad CUEs.

**Comment by saulfabregwiivc** [comment]
Like @carnage702 said, mainly these issues are caused by bad CUEs.

**Comment by eku** [comment]
I use the "official" redumps. If you would like to test with my version of the game, use site:archive.org [REDUMP] Disc Image Collection with your favourite search engine.

**Comment by Jimtsu** [comment]
Hi !

Same problem here, with the french version of the game [SLES02966].

I know with some PSX emulators and mostly with pal games, you need to put the appropriate SBI file with your bin/cue, so I've tried that but... still got nothing but a black screen.

If you need more information, don’t hesitate to ask!

Otherwise, I wanted to say that the performances are much better than before!
Bravo and thank you for your work! 👌

**Comment by eku** [comment]
> Edit : By patching each disc (the bin file) of the game with a ppf file, FFIX (FR) is now perfectly playable !

Do we know what is being patched? AP protection? Wouldn't that be the emulator's job?

**Comment by Jimtsu** [comment]
Yes, .ppf patches goal is to remove ap protection.
Normally, this is only useful if you want to play on a real console, to be able to run engraved games.

Don't know why this emulator require that, but hey, as long as it works...  ┐⁠(⁠ ⁠∵⁠ ⁠)⁠┌

.SBI files should be enough to run these games on most emulators (this is the case with duckstation, for example) but as far as I am concerned, it did not change anything here.

**Comment by saulfabregwiivc** [comment]
Commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/0021dcc67f84b36a46359cbe03ffd95489e8eed1 finally adds proper support for .SBI files on WiiStation for LibCrypt encrypted/protected games.

It will be avaliable in next build/version.

**Comment by eku** [comment]
> This includes the new commit for add .SBI files support for games which are encrypted/protected with LibCrypt.

How must the SBI files be named?

```
2012-12-30 18:00:05 ....A          452          SLES_029.67.sbi
2012-12-30 18:00:19 ....A          452          SLES_129.67.sbi
2012-12-30 18:00:33 ....A          452          SLES_229.67.sbi
2012-12-30 18:00:48 ....A          452          SLES_329.67.sbi
```

**Comment by xjsxjs197** [comment]
According to the code, it should be the following rule:
First, place the. sbi file and game files in the same directory.
If it's a single CD game, The name of the. sbi file is [the game name].sbi, for example FF IX.sbi.
If it's a multi CD game, The name of the. sbi file is [the game name]_n.sbi, for example FF IX disk1_1.sbi, FF IX disk2_2.sbi.



***@***.***
 
From: Erik Kunze
Date: 2023-12-08 00:26
To: xjsxjs197/WiiSXRX_2022
CC: xjsxjs197; State change
Subject: Re: [xjsxjs197/WiiSXRX_2022] FF IX (German/SLES02967) does not start (Issue #96)
This includes the new commit for add .SBI files support for games which are encrypted/protected with LibCrypt.
How must the SBI files be named?
2012-12-30 18:00:05 ....A          452          SLES_029.67.sbi
2012-12-30 18:00:19 ....A          452          SLES_129.67.sbi
2012-12-30 18:00:33 ....A          452          SLES_229.67.sbi
2012-12-30 18:00:48 ....A          452          SLES_329.67.sbi

**Comment by eku** [comment]
Hi @xjsxjs197,

thanks for the hint. If I rename the files as suggested, I get an error message in "ISO Info" ""LibCrypt protected game with missing SBI". If its named like the CUE/BIN than the error message is gone.

But the game still won't load. 

Would it be possible for you to try this out and debug it?

**Comment by xjsxjs197** [comment]
Can you share the iso file and. sbi file? Otherwise, there is no way to test it

**Comment by eku** [comment]
> Can you share the iso file and. sbi file? Otherwise, there is no way to test it

Sure. The ISO is at archive.org. Use `site:archive.org [REDUMP] Disc Image Collection`with startpage.com. As for the SBI files, use [redump.org](http://redump.org/downloads/).

**Comment by xjsxjs197** [comment]
[boot20231223.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13758601/boot20231223.zip)
The problem has been fixed. Please try this attachment. 
Final Fantasy IX (Germany) (Disc 1).sbi
I didn't correct the name of the SBI file, it has the same name as the Bin file.

**Comment by eku** [comment]
Thanks for the correction. The game now starts, albeit very slowly.

> I didn't correct the name of the SBI file

There's some strange handling of multi-disc games in the source.

https://github.com/xjsxjs197/WiiSXRX_2022/blob/main/cdriso.c#L1043

WiiStation apparently does not recognise games with multiple CDs as such. Are you planning to correct this?

Should I open an issue for it?

**Comment by saulfabregwiivc** [comment]
Not necessary.

Anyways, i think i've found the cause of the issue with SBI and multi-disks:

![Screenshot_20240110-103604_Chrome](https://github.com/xjsxjs197/WiiSXRX_2022/assets/66485640/a6b4ffb5-bea7-4d28-89ca-200017b59370)

This was taken from PCSX-ReARMed Libretro, but compare it to the actual implementation of Swap CD code on WiiStation, or even in WiiSX.

The cdrIsoMultidiskSelect command is missing here.
Anyways, i'll add it later.

**Comment by saulfabregwiivc** [comment]
@eku could you try this new build i've compiled here?
I added a small line of code in the loadISOSwap() logic for change the cdrIsoMultidiskSelect logic/command/variable when you swap a CD, which SBI detection logic uses for detect SBI of the multi-disks everytime the disc was changed.

https://github.com/saulfabregwiivc/WiiStation/commit/b490810e000cb96687294daad6ada57f28f7dff5

I made a PR for add that to WiiStation, but for now this should work.
[WiiStation_10012024.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13891200/WiiStation_10012024.zip)

**Comment by saulfabregwiivc** [comment]
@eku according to @notaz:
> I think this shouldn't be needed because according to nocash the protected sectors should be the same, i.e. the same .sbi should work for each disk of multidisk games.

There was a similar issue regarding this:
https://github.com/libretro/pcsx_rearmed/issues/179

**Comment by notaz** [comment]
> @eku according to @notaz:
> 
> > I think this shouldn't be needed because according to nocash the protected sectors should be the same, i.e. the same .sbi should work for each disk of multidisk games.
> 
> There was a similar issue regarding this: [libretro/pcsx_rearmed#179](https://github.com/libretro/pcsx_rearmed/issues/179)

I've updated this comment as it was not accurate, you actually **do** need separate files with a suffix like _1.sbi, _2.sbi etc. for pcsx_rearmed.

**Comment by saulfabregwiivc** [comment]
> > @eku according to @notaz:
> > > I think this shouldn't be needed because according to nocash the protected sectors should be the same, i.e. the same .sbi should work for each disk of multidisk games.
> > 
> > 
> > There was a similar issue regarding this: [libretro/pcsx_rearmed#179](https://github.com/libretro/pcsx_rearmed/issues/179)
> 
> I've updated this comment as it was not accurate, you actually **do** need separate files with a suffix like _1.sbi, _2.sbi etc. for pcsx_rearmed.

@notaz 

I saw your edited comment, but im not very clear with that.
So, how it should be named the SBIs for, this case, **Final Fantasy IX (Germany)**?
Considering that i have in this example:
- Final Fantasy IX (Germany) (Disc 1).cue
- Final Fantasy IX (Germany) (Disc 2).cue

So how do i should rename the SBI files for multi-disk games? Btw we're not using m3u files.

**Comment by notaz** [comment]
The `_N.sbi` suffixes are only for the .pbp format that can have all 4 CD images in one file. For others it's just [file].sbi, like `Final Fantasy IX (Germany) (Disc 1).sbi`, etc. in your case (at least for pcsx_rearmed, I haven't looked at this emu).

**Comment by saulfabregwiivc** [comment]
> The `_N.sbi` suffixes are only for the .pbp format that can have all 4 CD images in one file. For others it's just [file].sbi, like `Final Fantasy IX (Germany) (Disc 1).sbi`, etc. in your case (at least for pcsx_rearmed, I haven't looked at this emu).

Sorry for late reply, @notaz 

I just went and tried Final Fantasy VIII (Europe) using a CHD, and a SBI with the exact same name, and it actually loaded on WiiStation.
Thanks for your advice, as always. Keep going with your project PCSX-ReARMed!
