### ISSUE TITLE
Grandia (USA) (Disc 1) Exception thrown after first dinner sequence (beginning of the game)

### ISSUE THREAD

**Issue by MattMx** [xjsxjs197/WiiSXRX_2022#97]
**Game:**
Grandia (USA) (Disc 1) - which can be found by searching for "site:archive.org [REDUMP] Disc Image Collection" in any search engine.

**Exception:**
![image](https://github.com/xjsxjs197/WiiSXRX_2022/assets/18090498/d14a6555-f1dd-4d4d-a1cc-3b5c9222f77b)

**How to reproduce:**
Unavoidable loading screen after the first dinner sequence (which takes place at the beginning of the game).
The specific moment can be found at this moment in the YouTube walkthrough
https://youtu.be/SsfRQiOq0zk?list=PLP4T26mr-Fcs9jyzY8MUMYBTWJCMTvwk0&t=1885

**Comment by MattMx** [comment]
Some additional information:
Tested using the real BIOS (SCPH1001.BIN) loaded from SD card and with the "Boot Through Bios" option set to "Yes".
Tested using WiiStation_Ver2.0  released on April 25
[(https://github.com/xjsxjs197/WiiSXRX_2022/commit/1e7d3b5c11f2ccb471294b6612ac1f8e75874433)](https://github.com/xjsxjs197/WiiSXRX_2022/releases/tag/WiiStation_Ver2.0)

**Comment by MattMx** [comment]
Please find attached the save file for this title.
To replicate the issue you only need to:
1. Go up through the gate to exit the port area
2. Go forward along to the bridge to trigger a cutscene
3. After the cutscene is finished talk to the mother (behind the restaurant counter) twice.
4. During the second conversation ask Sue to tell the mother what you were doing to advance the plot.
5. The dinner sequence will start -> first make Sue talk then 3 times the mother so that she finishes her story.
6. Make the protagonist talk and say you are no longer hunger.
7. The screen will fade out.
8. Exception will be thrown.
[SCUS94457.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/11789304/SCUS94457.zip)

**Comment by MattMx** [comment]
Sadly release version 2.4 does not help.

**Comment by xjsxjs197** [comment]
Sorry for the late reply. I have made a lot of changes to the code recently, Try the following version to see if the problem still exists. 

[boot20231127.zip](https://github.com/xjsxjs197/WiiSXRX_2022/files/13470357/boot20231127.zip)

**Comment by MattMx** [comment]
Sadly this did not solve the problem on Lightrec 
![20231127_083614](https://github.com/xjsxjs197/WiiSXRX_2022/assets/18090498/05585c9d-586d-474b-aa26-22c7ac7ab6bc)

**Comment by MattMx** [comment]
Additionally I see that there is a slight synchronization problem between audio and video during cinematics. The video is slower than the music and out of sync. Although during gameplay the FPS count is still at 60 FPS. I'm not sure if it is Lightrec specific - I will need to test further.

**Comment by saulfabregwiivc** [comment]
Try using the improved PPC Dynarec (use Dynarec as core in Settings)

**Comment by MattMx** [comment]
Dynarec works great. No slowdown and no crashes. Thank you!
