### ISSUE TITLE
Question about required knowledge to help develop PSX emulator for Wii

### ISSUE THREAD

**Issue by maciejmaksymo** [xjsxjs197/WiiSXRX_2022#99]
Hello, 

I strongly believe in the potential of a PSX emulator for Wii. I'm a C# developer with some experience in C++. I would be very grateful for any pointers how to educate myself enough to be of any help in this project.
I'm currently going through this homebrew development tutorial for Wii 
https://youtu.be/noxGGdxHbDY
I can handle learning C++ development but what I'm missing is emulation specific knowledge. Are there any whitepapers available regarding this topic?

Any help would be appreciated.

Best regards,
Maciej

**Comment by xjsxjs197** [comment]
Thank you for following the Ps simulator on Wii.
I think interest and continuous investment of time and energy may be important. 
Here are some helpful documents.

Very detailed information about PS hardware
https://psx-spx.consoledev.net/

Useful suggestions provided by the author for efficient simulator Xebra
http://drhell.web.fc2.com/ps1/

In addition, ChatGpt is a very useful tool that can provide accurate answers to PS hardware or Libogc related questions.

Good luck.

**Comment by MattMx** [comment]
Thank you for your help!

**Comment by maciejmaksymo** [comment]
Thank you for your help

**Comment by xjsxjs197** [comment]
Temporarily close this. If you have any questions, feel free to consult me
